

CREATE TABLE "Agriculture" (
	plant_growth_med TEXT, 
	soil_horizon TEXT, 
	photosynt_activ TEXT, 
	photosynt_activ_meth TEXT, 
	samp_collect_method TEXT, 
	enrichment_protocol TEXT, 
	library_prep_kit TEXT, 
	sequencing_location TEXT, 
	soil_temp TEXT, 
	"soil_pH" FLOAT, 
	soil_conductivity TEXT, 
	rel_location TEXT, 
	soil_cover TEXT, 
	porosity TEXT, 
	texture TEXT, 
	texture_meth TEXT, 
	host_symbiont TEXT, 
	host_disease_stat TEXT, 
	pres_animal_insect TEXT, 
	plant_water_method TEXT, 
	anim_water_method TEXT, 
	farm_water_source TEXT, 
	water_source_shared TEXT, 
	"water_pH" FLOAT, 
	elev TEXT, 
	season TEXT, 
	solar_irradiance TEXT, 
	crop_yield TEXT, 
	season_humidity TEXT, 
	humidity TEXT, 
	adjacent_environment TEXT, 
	chem_administration TEXT NOT NULL, 
	food_prod TEXT, 
	lot_number TEXT, 
	fertilizer_admin TEXT, 
	samp_stor_temp TEXT, 
	food_trav_mode TEXT, 
	food_trav_vehic TEXT, 
	farm_equip_san TEXT, 
	farm_equip TEXT, 
	farm_equip_shared TEXT, 
	food_harvest_proc TEXT, 
	plant_struc TEXT, 
	host_dry_mass TEXT, 
	ances_data TEXT, 
	genetic_mod TEXT, 
	"Food_Product_type" TEXT, 
	"Food_source" TEXT NOT NULL, 
	spikein_strain TEXT, 
	organism_count TEXT, 
	size_frac_low TEXT, 
	size_frac_up TEXT, 
	cult_isol_date TEXT, 
	samp_pooling TEXT, 
	root_med_macronutr TEXT, 
	root_med_carbon TEXT, 
	root_med_ph FLOAT, 
	soil_depth TEXT, 
	specific_host TEXT NOT NULL, 
	pathogenicity TEXT NOT NULL, 
	biotic_relationship TEXT, 
	water_temp_regm TEXT, 
	watering_regm TEXT, 
	standing_water_regm TEXT, 
	gaseous_environment TEXT, 
	fungicide_regm TEXT, 
	climate_environment TEXT, 
	herbicide_regm TEXT, 
	non_mineral_nutr_regm TEXT, 
	pesticide_regm TEXT, 
	ph_regm TEXT, 
	salt_regm TEXT, 
	season_environment TEXT, 
	"temp" TEXT NOT NULL, 
	perturbation TEXT, 
	isol_growth_condt TEXT, 
	samp_store_dur TEXT NOT NULL, 
	samp_store_loc TEXT NOT NULL, 
	samp_collect_device TEXT NOT NULL, 
	samp_mat_process TEXT NOT NULL, 
	host_age TEXT NOT NULL, 
	host_common_name TEXT NOT NULL, 
	host_genotype TEXT NOT NULL, 
	host_height TEXT NOT NULL, 
	host_subspecf_genlin TEXT, 
	host_length TEXT NOT NULL, 
	host_life_stage TEXT NOT NULL, 
	host_phenotype TEXT NOT NULL, 
	host_taxid TEXT NOT NULL, 
	host_tot_mass TEXT NOT NULL, 
	host_spec_range INTEGER NOT NULL, 
	trophic_level TEXT, 
	plant_product TEXT, 
	samp_size TEXT NOT NULL, 
	oxy_stat_samp TEXT, 
	seq_meth TEXT NOT NULL, 
	samp_vol_we_dna_ext TEXT NOT NULL, 
	pcr_primers TEXT NOT NULL, 
	nucl_acid_ext TEXT NOT NULL, 
	nucl_acid_amp TEXT NOT NULL, 
	lib_size INTEGER, 
	lib_reads_seqd INTEGER NOT NULL, 
	lib_layout TEXT, 
	lib_vector TEXT NOT NULL, 
	lib_screen TEXT NOT NULL, 
	target_gene TEXT NOT NULL, 
	target_subfragment TEXT NOT NULL, 
	mid TEXT NOT NULL, 
	adapters TEXT NOT NULL, 
	pcr_cond TEXT NOT NULL, 
	seq_quality_check TEXT, 
	chimera_check TEXT NOT NULL, 
	assembly_name TEXT NOT NULL, 
	assembly_software TEXT, 
	assembly_quality TEXT, 
	annot TEXT, 
	url TEXT, 
	sop TEXT, 
	source_mat_id TEXT, 
	fao_class TEXT, 
	local_class TEXT, 
	local_class_meth TEXT, 
	soil_type TEXT NOT NULL, 
	soil_type_meth TEXT NOT NULL, 
	horizon TEXT, 
	horizon_meth TEXT, 
	link_class_info TEXT, 
	previous_land_use TEXT, 
	previous_land_use_meth TEXT, 
	crop_rotation TEXT, 
	agrochem_addition TEXT, 
	tillage TEXT, 
	fire TEXT, 
	flooding TEXT, 
	extreme_event TEXT, 
	link_climate_info TEXT, 
	annual_temp TEXT, 
	season_temp TEXT, 
	annual_precpt TEXT, 
	season_precpt TEXT, 
	cur_land_use TEXT, 
	slope_gradient TEXT, 
	slope_aspect TEXT, 
	profile_position TEXT, 
	drainage_class TEXT, 
	store_cond TEXT NOT NULL, 
	ph_meth TEXT, 
	cur_vegetation TEXT, 
	cur_vegetation_meth TEXT, 
	tot_org_carb TEXT, 
	tot_org_c_meth TEXT, 
	tot_nitro TEXT, 
	tot_n_meth TEXT, 
	microbial_biomass TEXT NOT NULL, 
	microbial_biomass_meth TEXT NOT NULL, 
	heavy_metals_meth TEXT, 
	tot_car TEXT, 
	tot_phos TEXT, 
	sieving TEXT NOT NULL, 
	pool_dna_extracts TEXT NOT NULL, 
	misc_param TEXT, 
	PRIMARY KEY (plant_growth_med, soil_horizon, photosynt_activ, photosynt_activ_meth, samp_collect_method, enrichment_protocol, library_prep_kit, sequencing_location, soil_temp, "soil_pH", soil_conductivity, rel_location, soil_cover, porosity, texture, texture_meth, host_symbiont, host_disease_stat, pres_animal_insect, plant_water_method, anim_water_method, farm_water_source, water_source_shared, "water_pH", elev, season, solar_irradiance, crop_yield, season_humidity, humidity, adjacent_environment, chem_administration, food_prod, lot_number, fertilizer_admin, samp_stor_temp, food_trav_mode, food_trav_vehic, farm_equip_san, farm_equip, farm_equip_shared, food_harvest_proc, plant_struc, host_dry_mass, ances_data, genetic_mod, "Food_Product_type", "Food_source", spikein_strain, organism_count, size_frac_low, size_frac_up, cult_isol_date, samp_pooling, root_med_macronutr, root_med_carbon, root_med_ph, soil_depth, specific_host, pathogenicity, biotic_relationship, water_temp_regm, watering_regm, standing_water_regm, gaseous_environment, fungicide_regm, climate_environment, herbicide_regm, non_mineral_nutr_regm, pesticide_regm, ph_regm, salt_regm, season_environment, "temp", perturbation, isol_growth_condt, samp_store_dur, samp_store_loc, samp_collect_device, samp_mat_process, host_age, host_common_name, host_genotype, host_height, host_subspecf_genlin, host_length, host_life_stage, host_phenotype, host_taxid, host_tot_mass, host_spec_range, trophic_level, plant_product, samp_size, oxy_stat_samp, seq_meth, samp_vol_we_dna_ext, pcr_primers, nucl_acid_ext, nucl_acid_amp, lib_size, lib_reads_seqd, lib_layout, lib_vector, lib_screen, target_gene, target_subfragment, mid, adapters, pcr_cond, seq_quality_check, chimera_check, assembly_name, assembly_software, assembly_quality, annot, url, sop, source_mat_id, fao_class, local_class, local_class_meth, soil_type, soil_type_meth, horizon, horizon_meth, link_class_info, previous_land_use, previous_land_use_meth, crop_rotation, agrochem_addition, tillage, fire, flooding, extreme_event, link_climate_info, annual_temp, season_temp, annual_precpt, season_precpt, cur_land_use, slope_gradient, slope_aspect, profile_position, drainage_class, store_cond, ph_meth, cur_vegetation, cur_vegetation_meth, tot_org_carb, tot_org_c_meth, tot_nitro, tot_n_meth, microbial_biomass, microbial_biomass_meth, heavy_metals_meth, tot_car, tot_phos, sieving, pool_dna_extracts, misc_param)
);

CREATE TABLE "Air" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	alt TEXT NOT NULL, 
	elev TEXT, 
	barometric_press TEXT, 
	carb_dioxide TEXT, 
	carb_monoxide TEXT, 
	chem_administration TEXT, 
	humidity TEXT, 
	methane TEXT, 
	organism_count TEXT, 
	oxygen TEXT, 
	oxy_stat_samp TEXT, 
	perturbation TEXT, 
	pollutants TEXT, 
	air_particulate_matter_concentration TEXT, 
	salinity TEXT, 
	samp_store_dur TEXT, 
	samp_store_loc TEXT, 
	samp_store_temp TEXT, 
	samp_vol_we_dna_ext TEXT, 
	solar_irradiance TEXT, 
	"temp" TEXT, 
	ventilation_rate TEXT, 
	ventilation_type TEXT, 
	volatile_org_comp TEXT, 
	wind_direction TEXT, 
	wind_speed TEXT, 
	misc_param TEXT, 
	PRIMARY KEY (samp_name, project_name, alt, elev, barometric_press, carb_dioxide, carb_monoxide, chem_administration, humidity, methane, organism_count, oxygen, oxy_stat_samp, perturbation, pollutants, air_particulate_matter_concentration, salinity, samp_store_dur, samp_store_loc, samp_store_temp, samp_vol_we_dna_ext, solar_irradiance, "temp", ventilation_rate, ventilation_type, volatile_org_comp, wind_direction, wind_speed, misc_param)
);

CREATE TABLE "BuiltEnvironment" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	surf_material TEXT, 
	surf_air_cont TEXT, 
	rel_air_humidity TEXT NOT NULL, 
	abs_air_humidity TEXT NOT NULL, 
	surf_humidity TEXT, 
	air_temp TEXT NOT NULL, 
	surf_temp TEXT, 
	surf_moisture_ph FLOAT, 
	build_occup_type TEXT NOT NULL, 
	surf_moisture TEXT, 
	dew_point TEXT, 
	carb_dioxide TEXT NOT NULL, 
	ventilation_type TEXT NOT NULL, 
	organism_count TEXT NOT NULL, 
	indoor_space TEXT NOT NULL, 
	indoor_surf TEXT, 
	filter_type TEXT NOT NULL, 
	heat_cool_type TEXT NOT NULL, 
	substructure_type TEXT, 
	building_setting TEXT NOT NULL, 
	light_type TEXT NOT NULL, 
	samp_sort_meth TEXT, 
	space_typ_state TEXT NOT NULL, 
	typ_occup_density FLOAT NOT NULL, 
	occup_samp INTEGER NOT NULL, 
	occup_density_samp TEXT NOT NULL, 
	address TEXT, 
	adj_room TEXT, 
	aero_struc TEXT, 
	amount_light TEXT, 
	arch_struc TEXT, 
	avg_occup FLOAT, 
	avg_dew_point TEXT, 
	avg_temp TEXT, 
	bathroom_count INTEGER, 
	bedroom_count INTEGER, 
	built_struc_age TEXT, 
	built_struc_set TEXT, 
	built_struc_type TEXT, 
	ceil_area TEXT, 
	ceil_cond TEXT, 
	ceil_finish_mat TEXT, 
	ceil_water_mold TEXT, 
	ceil_struc TEXT, 
	ceil_texture TEXT, 
	ceil_thermal_mass TEXT, 
	ceil_type TEXT, 
	cool_syst_id INTEGER, 
	date_last_rain TEXT, 
	build_docs TEXT, 
	door_size TEXT, 
	door_cond TEXT, 
	door_direct TEXT, 
	door_loc TEXT, 
	door_mat TEXT, 
	door_move TEXT, 
	door_water_mold TEXT, 
	door_type TEXT, 
	door_comp_type TEXT, 
	door_type_metal TEXT, 
	door_type_wood TEXT, 
	drawings TEXT, 
	elevator INTEGER, 
	escalator INTEGER, 
	exp_duct TEXT, 
	exp_pipe INTEGER, 
	ext_door INTEGER, 
	fireplace_type TEXT, 
	floor_age TEXT, 
	floor_area TEXT, 
	floor_cond TEXT, 
	floor_count INTEGER, 
	floor_finish_mat TEXT, 
	floor_water_mold TEXT, 
	floor_struc TEXT, 
	floor_thermal_mass TEXT, 
	freq_clean TEXT, 
	freq_cook INTEGER, 
	furniture TEXT, 
	gender_restroom TEXT, 
	hall_count INTEGER, 
	handidness TEXT, 
	heat_deliv_loc TEXT, 
	heat_sys_deliv_meth TEXT, 
	heat_system_id INTEGER, 
	height_carper_fiber TEXT, 
	inside_lux TEXT, 
	int_wall_cond TEXT, 
	last_clean TEXT, 
	max_occup INTEGER, 
	mech_struc TEXT, 
	number_plants INTEGER, 
	number_pets INTEGER, 
	number_resident INTEGER, 
	occup_document TEXT, 
	ext_wall_orient TEXT, 
	ext_window_orient TEXT, 
	rel_humidity_out TEXT, 
	pres_animal_insect TEXT, 
	quad_pos TEXT, 
	rel_samp_loc TEXT, 
	room_air_exch_rate TEXT, 
	room_architec_elem TEXT, 
	room_condt TEXT, 
	room_count INTEGER, 
	room_dim TEXT, 
	room_door_dist TEXT, 
	room_loc TEXT, 
	room_moist_dam_hist INTEGER, 
	room_net_area TEXT, 
	room_occup INTEGER, 
	room_samp_pos TEXT, 
	room_type TEXT, 
	room_vol TEXT, 
	room_window_count INTEGER, 
	room_connected TEXT, 
	room_hallway TEXT, 
	room_door_share TEXT, 
	room_wall_share TEXT, 
	samp_weather TEXT, 
	samp_floor TEXT, 
	samp_room_id INTEGER, 
	samp_time_out TEXT, 
	season TEXT, 
	season_use TEXT, 
	shading_device_cond TEXT, 
	shading_device_loc TEXT, 
	shading_device_mat TEXT, 
	shad_dev_water_mold TEXT, 
	shading_device_type TEXT, 
	specific_humidity TEXT, 
	specific TEXT, 
	temp_out TEXT, 
	train_line TEXT, 
	train_stat_loc TEXT, 
	train_stop_loc TEXT, 
	vis_media TEXT, 
	wall_area TEXT, 
	wall_const_type TEXT, 
	wall_finish_mat TEXT, 
	wall_height TEXT, 
	wall_loc TEXT, 
	wall_water_mold TEXT, 
	wall_surf_treatment TEXT, 
	wall_texture TEXT, 
	wall_thermal_mass TEXT, 
	water_feat_size TEXT, 
	water_feat_type TEXT, 
	weekday TEXT, 
	window_size TEXT, 
	window_cond TEXT, 
	window_cover TEXT, 
	window_horiz_pos TEXT, 
	window_loc TEXT, 
	window_mat TEXT, 
	window_open_freq INTEGER, 
	window_water_mold TEXT, 
	window_status TEXT, 
	window_type TEXT, 
	window_vert_pos TEXT, 
	PRIMARY KEY (samp_name, project_name, surf_material, surf_air_cont, rel_air_humidity, abs_air_humidity, surf_humidity, air_temp, surf_temp, surf_moisture_ph, build_occup_type, surf_moisture, dew_point, carb_dioxide, ventilation_type, organism_count, indoor_space, indoor_surf, filter_type, heat_cool_type, substructure_type, building_setting, light_type, samp_sort_meth, space_typ_state, typ_occup_density, occup_samp, occup_density_samp, address, adj_room, aero_struc, amount_light, arch_struc, avg_occup, avg_dew_point, avg_temp, bathroom_count, bedroom_count, built_struc_age, built_struc_set, built_struc_type, ceil_area, ceil_cond, ceil_finish_mat, ceil_water_mold, ceil_struc, ceil_texture, ceil_thermal_mass, ceil_type, cool_syst_id, date_last_rain, build_docs, door_size, door_cond, door_direct, door_loc, door_mat, door_move, door_water_mold, door_type, door_comp_type, door_type_metal, door_type_wood, drawings, elevator, escalator, exp_duct, exp_pipe, ext_door, fireplace_type, floor_age, floor_area, floor_cond, floor_count, floor_finish_mat, floor_water_mold, floor_struc, floor_thermal_mass, freq_clean, freq_cook, furniture, gender_restroom, hall_count, handidness, heat_deliv_loc, heat_sys_deliv_meth, heat_system_id, height_carper_fiber, inside_lux, int_wall_cond, last_clean, max_occup, mech_struc, number_plants, number_pets, number_resident, occup_document, ext_wall_orient, ext_window_orient, rel_humidity_out, pres_animal_insect, quad_pos, rel_samp_loc, room_air_exch_rate, room_architec_elem, room_condt, room_count, room_dim, room_door_dist, room_loc, room_moist_dam_hist, room_net_area, room_occup, room_samp_pos, room_type, room_vol, room_window_count, room_connected, room_hallway, room_door_share, room_wall_share, samp_weather, samp_floor, samp_room_id, samp_time_out, season, season_use, shading_device_cond, shading_device_loc, shading_device_mat, shad_dev_water_mold, shading_device_type, specific_humidity, specific, temp_out, train_line, train_stat_loc, train_stop_loc, vis_media, wall_area, wall_const_type, wall_finish_mat, wall_height, wall_loc, wall_water_mold, wall_surf_treatment, wall_texture, wall_thermal_mass, water_feat_size, water_feat_type, weekday, window_size, window_cond, window_cover, window_horiz_pos, window_loc, window_mat, window_open_freq, window_water_mold, window_status, window_type, window_vert_pos)
);

CREATE TABLE "Database" (
	agriculture_set TEXT, 
	air_set TEXT, 
	built_environment_set TEXT, 
	checklist_set TEXT, 
	environmental_package_set TEXT, 
	food_animal_and_animal_feed_set TEXT, 
	food_farm_environment_set TEXT, 
	food_food_production_facility_set TEXT, 
	food_human_foods_set TEXT, 
	host_associated_set TEXT, 
	human_associated_set TEXT, 
	human_gut_set TEXT, 
	human_oral_set TEXT, 
	human_skin_set TEXT, 
	human_vaginal_set TEXT, 
	hydrocarbon_resources_cores_set TEXT, 
	hydrocarbon_resources_fluids_swabs_set TEXT, 
	microbial_mat_biofilm_set TEXT, 
	migs_ba_set TEXT, 
	migs_ba_plant_associated_set TEXT, 
	migs_ba_sediment_set TEXT, 
	migs_ba_soil_set TEXT, 
	mims_plant_associated_set TEXT, 
	mims_sediment_set TEXT, 
	mims_soil_set TEXT, 
	plant_associated_set TEXT, 
	sediment_set TEXT, 
	soil_set TEXT, 
	symbiont_associated_set TEXT, 
	unknown_term_set TEXT, 
	wastewater_sludge_set TEXT, 
	water_set TEXT, 
	PRIMARY KEY (agriculture_set, air_set, built_environment_set, checklist_set, environmental_package_set, food_animal_and_animal_feed_set, food_farm_environment_set, food_food_production_facility_set, food_human_foods_set, host_associated_set, human_associated_set, human_gut_set, human_oral_set, human_skin_set, human_vaginal_set, hydrocarbon_resources_cores_set, hydrocarbon_resources_fluids_swabs_set, microbial_mat_biofilm_set, migs_ba_set, migs_ba_plant_associated_set, migs_ba_sediment_set, migs_ba_soil_set, mims_plant_associated_set, mims_sediment_set, mims_soil_set, plant_associated_set, sediment_set, soil_set, symbiont_associated_set, unknown_term_set, wastewater_sludge_set, water_set)
);

CREATE TABLE "FoodAnimalAndAnimalFeed" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	lat_lon TEXT NOT NULL, 
	geo_loc_name TEXT NOT NULL, 
	collection_date TEXT NOT NULL, 
	env_broad_scale TEXT NOT NULL, 
	env_local_scale TEXT NOT NULL, 
	env_medium TEXT NOT NULL, 
	seq_meth TEXT NOT NULL, 
	samp_size TEXT, 
	samp_collect_device TEXT, 
	experimental_factor TEXT, 
	nucl_acid_ext TEXT, 
	organism_count TEXT, 
	spikein_count TEXT, 
	samp_stor_temp TEXT, 
	samp_stor_dur TEXT, 
	samp_vol_we_dna_ext TEXT, 
	pool_dna_extracts TEXT, 
	"temp" TEXT, 
	samp_stor_loc TEXT, 
	samp_transport_cont TEXT, 
	perturbation TEXT, 
	coll_site_geo_feat TEXT NOT NULL, 
	food_origin TEXT NOT NULL, 
	food_prod TEXT NOT NULL, 
	food_product_type TEXT NOT NULL, 
	food_source TEXT, 
	"IFSAC_category" TEXT NOT NULL, 
	intended_consumer TEXT NOT NULL, 
	samp_purpose TEXT NOT NULL, 
	animal_am TEXT, 
	animal_am_dur TEXT, 
	animal_am_freq TEXT, 
	animal_am_route TEXT, 
	animal_am_use TEXT, 
	animal_body_cond TEXT, 
	animal_diet TEXT, 
	animal_feed_equip TEXT, 
	animal_group_size INTEGER, 
	animal_housing TEXT, 
	animal_sex TEXT, 
	bacterial_density TEXT, 
	cons_food_stor_dur TEXT, 
	cons_food_stor_temp TEXT, 
	cons_purch_date TEXT, 
	cons_qty_purchased TEXT, 
	cult_isol_date TEXT, 
	cult_result TEXT, 
	cult_result_org TEXT, 
	cult_target TEXT, 
	enrichment_protocol TEXT, 
	food_additive TEXT, 
	food_contact_surf TEXT, 
	food_contain_wrap TEXT, 
	food_cooking_proc TEXT, 
	food_dis_point TEXT, 
	food_dis_point_city TEXT, 
	food_ingredient TEXT, 
	food_pack_capacity TEXT, 
	food_pack_integrity TEXT, 
	food_pack_medium TEXT, 
	food_preserv_proc TEXT, 
	food_prior_contact TEXT, 
	food_prod_synonym TEXT, 
	food_product_qual TEXT, 
	food_quality_date TEXT, 
	food_source_age TEXT, 
	food_trace_list TEXT, 
	food_trav_mode TEXT, 
	food_trav_vehic TEXT, 
	food_treat_proc TEXT, 
	"HACCP_term" TEXT, 
	library_prep_kit TEXT, 
	lot_number TEXT, 
	microb_cult_med TEXT, 
	part_plant_animal TEXT, 
	repository_name TEXT, 
	samp_collect_method TEXT, 
	samp_pooling TEXT, 
	samp_rep_biol TEXT, 
	samp_rep_tech TEXT, 
	samp_source_mat_cat TEXT, 
	samp_stor_device TEXT, 
	samp_stor_media TEXT, 
	samp_transport_dur TEXT, 
	samp_transport_temp TEXT, 
	sequencing_kit TEXT, 
	sequencing_location TEXT, 
	serovar_or_serotype TEXT, 
	"spikein_AMR" TEXT, 
	spikein_antibiotic TEXT, 
	spikein_growth_med TEXT, 
	spikein_metal TEXT, 
	spikein_org TEXT, 
	spikein_serovar TEXT, 
	spikein_strain TEXT, 
	study_design TEXT, 
	study_inc_dur TEXT, 
	study_inc_temp TEXT, 
	study_timecourse TEXT, 
	study_tmnt TEXT, 
	timepoint TEXT, 
	misc_param TEXT, 
	PRIMARY KEY (samp_name, project_name, lat_lon, geo_loc_name, collection_date, env_broad_scale, env_local_scale, env_medium, seq_meth, samp_size, samp_collect_device, experimental_factor, nucl_acid_ext, organism_count, spikein_count, samp_stor_temp, samp_stor_dur, samp_vol_we_dna_ext, pool_dna_extracts, "temp", samp_stor_loc, samp_transport_cont, perturbation, coll_site_geo_feat, food_origin, food_prod, food_product_type, food_source, "IFSAC_category", intended_consumer, samp_purpose, animal_am, animal_am_dur, animal_am_freq, animal_am_route, animal_am_use, animal_body_cond, animal_diet, animal_feed_equip, animal_group_size, animal_housing, animal_sex, bacterial_density, cons_food_stor_dur, cons_food_stor_temp, cons_purch_date, cons_qty_purchased, cult_isol_date, cult_result, cult_result_org, cult_target, enrichment_protocol, food_additive, food_contact_surf, food_contain_wrap, food_cooking_proc, food_dis_point, food_dis_point_city, food_ingredient, food_pack_capacity, food_pack_integrity, food_pack_medium, food_preserv_proc, food_prior_contact, food_prod_synonym, food_product_qual, food_quality_date, food_source_age, food_trace_list, food_trav_mode, food_trav_vehic, food_treat_proc, "HACCP_term", library_prep_kit, lot_number, microb_cult_med, part_plant_animal, repository_name, samp_collect_method, samp_pooling, samp_rep_biol, samp_rep_tech, samp_source_mat_cat, samp_stor_device, samp_stor_media, samp_transport_dur, samp_transport_temp, sequencing_kit, sequencing_location, serovar_or_serotype, "spikein_AMR", spikein_antibiotic, spikein_growth_med, spikein_metal, spikein_org, spikein_serovar, spikein_strain, study_design, study_inc_dur, study_inc_temp, study_timecourse, study_tmnt, timepoint, misc_param)
);

CREATE TABLE "FoodFarmEnvironment" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	lat_lon TEXT NOT NULL, 
	geo_loc_name TEXT NOT NULL, 
	collection_date TEXT NOT NULL, 
	env_broad_scale TEXT NOT NULL, 
	env_local_scale TEXT NOT NULL, 
	env_medium TEXT NOT NULL, 
	seq_meth TEXT NOT NULL, 
	samp_size TEXT, 
	samp_collect_device TEXT, 
	nucl_acid_ext TEXT, 
	humidity TEXT, 
	organism_count TEXT, 
	spikein_count TEXT, 
	samp_stor_temp TEXT, 
	solar_irradiance TEXT, 
	ventilation_rate TEXT, 
	samp_stor_dur TEXT, 
	wind_speed TEXT, 
	salinity TEXT, 
	samp_vol_we_dna_ext TEXT, 
	previous_land_use TEXT, 
	crop_rotation TEXT, 
	soil_type_meth TEXT, 
	tot_org_c_meth TEXT, 
	tot_nitro_cont_meth TEXT, 
	salinity_meth TEXT, 
	host_age TEXT, 
	host_dry_mass TEXT, 
	host_height TEXT, 
	host_length TEXT, 
	host_tot_mass TEXT, 
	root_med_carbon TEXT, 
	root_med_macronutr TEXT, 
	root_med_micronutr TEXT, 
	depth TEXT NOT NULL, 
	season_temp TEXT, 
	season_precpt TEXT, 
	tot_org_carb TEXT, 
	tot_nitro_content TEXT, 
	conduc TEXT, 
	turbidity TEXT, 
	size_frac_low TEXT, 
	size_frac_up TEXT, 
	"temp" TEXT, 
	ventilation_type TEXT, 
	wind_direction TEXT, 
	genetic_mod TEXT, 
	host_phenotype TEXT, 
	ph FLOAT, 
	ances_data TEXT, 
	biotic_regm TEXT NOT NULL, 
	chem_administration TEXT NOT NULL, 
	growth_habit TEXT, 
	host_disease_stat TEXT, 
	host_genotype TEXT, 
	host_taxid TEXT, 
	mechanical_damage TEXT, 
	perturbation TEXT, 
	root_cond TEXT, 
	root_med_ph FLOAT, 
	tillage TEXT, 
	ph_meth TEXT, 
	growth_medium TEXT, 
	season TEXT, 
	food_product_type TEXT NOT NULL, 
	samp_type TEXT NOT NULL, 
	farm_water_source TEXT, 
	plant_water_method TEXT, 
	"air_PM_concen" TEXT, 
	animal_feed_equip TEXT, 
	animal_intrusion TEXT, 
	anim_water_method TEXT, 
	crop_yield TEXT, 
	cult_result TEXT, 
	cult_result_org TEXT, 
	cult_target TEXT, 
	plant_part_maturity TEXT, 
	adjacent_environment TEXT, 
	water_source_adjac TEXT, 
	farm_equip_shared TEXT, 
	farm_equip_san TEXT, 
	farm_equip_san_freq TEXT, 
	farm_equip TEXT, 
	fertilizer_admin TEXT, 
	fertilizer_date TEXT, 
	animal_group_size INTEGER, 
	animal_diet TEXT, 
	food_contact_surf TEXT, 
	food_contain_wrap TEXT, 
	food_harvest_proc TEXT, 
	food_pack_medium TEXT, 
	food_preserv_proc TEXT, 
	food_prod_char TEXT, 
	prod_label_claims TEXT, 
	food_trav_mode TEXT, 
	food_trav_vehic TEXT, 
	food_source TEXT, 
	food_treat_proc TEXT, 
	extr_weather_event TEXT, 
	date_extr_weath TEXT, 
	host_subspecf_genlin TEXT, 
	intended_consumer TEXT, 
	library_prep_kit TEXT, 
	air_flow_impede TEXT, 
	lot_number TEXT, 
	season_humidity TEXT, 
	part_plant_animal TEXT, 
	plant_growth_med TEXT, 
	plant_reprod_crop TEXT, 
	samp_purpose TEXT, 
	repository_name TEXT, 
	samp_pooling TEXT, 
	samp_source_mat_cat TEXT, 
	sequencing_kit TEXT, 
	sequencing_location TEXT, 
	serovar_or_serotype TEXT, 
	soil_conductivity TEXT, 
	soil_cover TEXT, 
	"soil_pH" FLOAT, 
	rel_location TEXT, 
	soil_porosity TEXT, 
	soil_temp TEXT, 
	soil_texture_class TEXT, 
	soil_texture_meth TEXT, 
	soil_type TEXT, 
	spikein_org TEXT, 
	spikein_serovar TEXT, 
	spikein_growth_med TEXT, 
	spikein_strain TEXT, 
	spikein_antibiotic TEXT, 
	spikein_metal TEXT, 
	timepoint TEXT, 
	water_frequency TEXT, 
	"water_pH" FLOAT, 
	water_source_shared TEXT, 
	enrichment_protocol TEXT, 
	food_quality_date TEXT, 
	"IFSAC_category" TEXT NOT NULL, 
	animal_housing TEXT, 
	cult_isol_date TEXT, 
	food_clean_proc TEXT, 
	misc_param TEXT, 
	PRIMARY KEY (samp_name, project_name, lat_lon, geo_loc_name, collection_date, env_broad_scale, env_local_scale, env_medium, seq_meth, samp_size, samp_collect_device, nucl_acid_ext, humidity, organism_count, spikein_count, samp_stor_temp, solar_irradiance, ventilation_rate, samp_stor_dur, wind_speed, salinity, samp_vol_we_dna_ext, previous_land_use, crop_rotation, soil_type_meth, tot_org_c_meth, tot_nitro_cont_meth, salinity_meth, host_age, host_dry_mass, host_height, host_length, host_tot_mass, root_med_carbon, root_med_macronutr, root_med_micronutr, depth, season_temp, season_precpt, tot_org_carb, tot_nitro_content, conduc, turbidity, size_frac_low, size_frac_up, "temp", ventilation_type, wind_direction, genetic_mod, host_phenotype, ph, ances_data, biotic_regm, chem_administration, growth_habit, host_disease_stat, host_genotype, host_taxid, mechanical_damage, perturbation, root_cond, root_med_ph, tillage, ph_meth, growth_medium, season, food_product_type, samp_type, farm_water_source, plant_water_method, "air_PM_concen", animal_feed_equip, animal_intrusion, anim_water_method, crop_yield, cult_result, cult_result_org, cult_target, plant_part_maturity, adjacent_environment, water_source_adjac, farm_equip_shared, farm_equip_san, farm_equip_san_freq, farm_equip, fertilizer_admin, fertilizer_date, animal_group_size, animal_diet, food_contact_surf, food_contain_wrap, food_harvest_proc, food_pack_medium, food_preserv_proc, food_prod_char, prod_label_claims, food_trav_mode, food_trav_vehic, food_source, food_treat_proc, extr_weather_event, date_extr_weath, host_subspecf_genlin, intended_consumer, library_prep_kit, air_flow_impede, lot_number, season_humidity, part_plant_animal, plant_growth_med, plant_reprod_crop, samp_purpose, repository_name, samp_pooling, samp_source_mat_cat, sequencing_kit, sequencing_location, serovar_or_serotype, soil_conductivity, soil_cover, "soil_pH", rel_location, soil_porosity, soil_temp, soil_texture_class, soil_texture_meth, soil_type, spikein_org, spikein_serovar, spikein_growth_med, spikein_strain, spikein_antibiotic, spikein_metal, timepoint, water_frequency, "water_pH", water_source_shared, enrichment_protocol, food_quality_date, "IFSAC_category", animal_housing, cult_isol_date, food_clean_proc, misc_param)
);

CREATE TABLE "FoodFoodProductionFacility" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	lat_lon TEXT NOT NULL, 
	geo_loc_name TEXT NOT NULL, 
	collection_date TEXT NOT NULL, 
	env_broad_scale TEXT NOT NULL, 
	env_local_scale TEXT NOT NULL, 
	env_medium TEXT NOT NULL, 
	seq_meth TEXT NOT NULL, 
	samp_size TEXT, 
	samp_collect_device TEXT, 
	experimental_factor TEXT, 
	nucl_acid_ext TEXT, 
	organism_count TEXT, 
	samp_stor_temp TEXT, 
	samp_stor_dur TEXT, 
	air_temp TEXT, 
	room_dim TEXT, 
	freq_clean TEXT, 
	samp_room_id INTEGER, 
	samp_vol_we_dna_ext TEXT, 
	pool_dna_extracts TEXT, 
	samp_stor_loc TEXT, 
	surf_material TEXT, 
	indoor_surf TEXT, 
	avg_occup FLOAT, 
	samp_floor TEXT, 
	genetic_mod TEXT, 
	coll_site_geo_feat TEXT NOT NULL, 
	samp_source_mat_cat TEXT NOT NULL, 
	samp_type TEXT NOT NULL, 
	samp_stor_media TEXT NOT NULL, 
	samp_stor_device TEXT NOT NULL, 
	food_product_type TEXT NOT NULL, 
	"IFSAC_category" TEXT NOT NULL, 
	food_product_qual TEXT NOT NULL, 
	food_contact_surf TEXT NOT NULL, 
	facility_type TEXT, 
	food_trav_mode TEXT, 
	food_trav_vehic TEXT, 
	samp_transport_dur TEXT, 
	samp_transport_temp TEXT, 
	samp_collect_method TEXT, 
	num_samp_collect TEXT, 
	lot_number TEXT, 
	hygienic_area TEXT, 
	env_monitoring_zone TEXT, 
	area_samp_size TEXT, 
	samp_surf_moisture TEXT, 
	samp_loc_condition TEXT, 
	biocide_used TEXT, 
	ster_meth_samp_room TEXT, 
	enrichment_protocol TEXT, 
	cult_target TEXT, 
	microb_cult_med TEXT, 
	timepoint TEXT, 
	bacterial_density TEXT, 
	cult_isol_date TEXT, 
	cult_result TEXT, 
	cult_result_org TEXT, 
	subspecf_gen_lin TEXT, 
	samp_pooling TEXT, 
	samp_purpose TEXT, 
	samp_rep_tech TEXT, 
	samp_rep_biol TEXT, 
	samp_transport_cont TEXT, 
	study_design TEXT, 
	nucl_acid_ext_kit TEXT, 
	library_prep_kit TEXT, 
	sequencing_kit TEXT, 
	sequencing_location TEXT, 
	study_inc_temp TEXT, 
	study_inc_dur TEXT, 
	study_timecourse TEXT, 
	study_tmnt TEXT, 
	food_source TEXT, 
	food_dis_point TEXT, 
	food_dis_point_city TEXT, 
	food_origin TEXT, 
	food_prod_synonym TEXT, 
	food_additive TEXT, 
	food_trace_list TEXT, 
	part_plant_animal TEXT, 
	food_ingredient TEXT, 
	spec_intended_cons TEXT, 
	"HACCP_term" TEXT, 
	dietary_claim_use TEXT, 
	food_allergen_label TEXT, 
	food_prod_char TEXT, 
	prod_label_claims TEXT, 
	food_name_status TEXT, 
	food_preserv_proc TEXT, 
	food_cooking_proc TEXT, 
	food_treat_proc TEXT, 
	food_contain_wrap TEXT, 
	food_pack_capacity TEXT, 
	food_pack_medium TEXT, 
	food_prior_contact TEXT, 
	food_prod TEXT, 
	food_quality_date TEXT, 
	repository_name TEXT, 
	intended_consumer TEXT, 
	food_pack_integrity TEXT, 
	misc_param TEXT, 
	PRIMARY KEY (samp_name, project_name, lat_lon, geo_loc_name, collection_date, env_broad_scale, env_local_scale, env_medium, seq_meth, samp_size, samp_collect_device, experimental_factor, nucl_acid_ext, organism_count, samp_stor_temp, samp_stor_dur, air_temp, room_dim, freq_clean, samp_room_id, samp_vol_we_dna_ext, pool_dna_extracts, samp_stor_loc, surf_material, indoor_surf, avg_occup, samp_floor, genetic_mod, coll_site_geo_feat, samp_source_mat_cat, samp_type, samp_stor_media, samp_stor_device, food_product_type, "IFSAC_category", food_product_qual, food_contact_surf, facility_type, food_trav_mode, food_trav_vehic, samp_transport_dur, samp_transport_temp, samp_collect_method, num_samp_collect, lot_number, hygienic_area, env_monitoring_zone, area_samp_size, samp_surf_moisture, samp_loc_condition, biocide_used, ster_meth_samp_room, enrichment_protocol, cult_target, microb_cult_med, timepoint, bacterial_density, cult_isol_date, cult_result, cult_result_org, subspecf_gen_lin, samp_pooling, samp_purpose, samp_rep_tech, samp_rep_biol, samp_transport_cont, study_design, nucl_acid_ext_kit, library_prep_kit, sequencing_kit, sequencing_location, study_inc_temp, study_inc_dur, study_timecourse, study_tmnt, food_source, food_dis_point, food_dis_point_city, food_origin, food_prod_synonym, food_additive, food_trace_list, part_plant_animal, food_ingredient, spec_intended_cons, "HACCP_term", dietary_claim_use, food_allergen_label, food_prod_char, prod_label_claims, food_name_status, food_preserv_proc, food_cooking_proc, food_treat_proc, food_contain_wrap, food_pack_capacity, food_pack_medium, food_prior_contact, food_prod, food_quality_date, repository_name, intended_consumer, food_pack_integrity, misc_param)
);

CREATE TABLE "FoodHumanFoods" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	lat_lon TEXT NOT NULL, 
	geo_loc_name TEXT NOT NULL, 
	collection_date TEXT NOT NULL, 
	env_broad_scale TEXT NOT NULL, 
	env_local_scale TEXT NOT NULL, 
	env_medium TEXT NOT NULL, 
	seq_meth TEXT NOT NULL, 
	samp_size TEXT, 
	samp_collect_device TEXT, 
	experimental_factor TEXT, 
	nucl_acid_ext TEXT, 
	organism_count TEXT, 
	spikein_count TEXT, 
	samp_stor_temp TEXT, 
	samp_stor_dur TEXT, 
	samp_vol_we_dna_ext TEXT, 
	pool_dna_extracts TEXT, 
	"temp" TEXT, 
	samp_stor_loc TEXT, 
	genetic_mod TEXT, 
	perturbation TEXT, 
	coll_site_geo_feat TEXT NOT NULL, 
	food_product_type TEXT NOT NULL, 
	"IFSAC_category" TEXT NOT NULL, 
	ferm_chem_add TEXT, 
	ferm_chem_add_perc TEXT, 
	ferm_headspace_oxy TEXT, 
	ferm_medium TEXT, 
	"ferm_pH" FLOAT, 
	ferm_rel_humidity TEXT, 
	ferm_temp TEXT, 
	ferm_time TEXT, 
	ferm_vessel TEXT, 
	bacterial_density TEXT, 
	cons_food_stor_dur TEXT, 
	cons_food_stor_temp TEXT, 
	cons_purch_date TEXT, 
	cons_qty_purchased TEXT, 
	cult_isol_date TEXT, 
	cult_result TEXT, 
	cult_result_org TEXT, 
	cult_target TEXT, 
	dietary_claim_use TEXT, 
	enrichment_protocol TEXT, 
	food_additive TEXT, 
	food_allergen_label TEXT, 
	food_contact_surf TEXT, 
	food_contain_wrap TEXT, 
	food_cooking_proc TEXT, 
	food_dis_point TEXT, 
	food_ingredient TEXT, 
	food_name_status TEXT, 
	food_origin TEXT, 
	food_pack_capacity TEXT, 
	food_pack_integrity TEXT, 
	food_pack_medium TEXT, 
	food_preserv_proc TEXT, 
	food_prior_contact TEXT, 
	food_prod TEXT, 
	food_prod_synonym TEXT, 
	food_product_qual TEXT, 
	food_quality_date TEXT, 
	food_source TEXT, 
	food_trace_list TEXT, 
	food_trav_mode TEXT, 
	food_trav_vehic TEXT, 
	food_treat_proc TEXT, 
	"HACCP_term" TEXT, 
	intended_consumer TEXT, 
	library_prep_kit TEXT, 
	lot_number TEXT, 
	microb_cult_med TEXT, 
	microb_start TEXT, 
	microb_start_count TEXT, 
	microb_start_inoc TEXT, 
	microb_start_prep TEXT, 
	microb_start_source TEXT, 
	"microb_start_taxID" TEXT, 
	nucl_acid_ext_kit TEXT, 
	num_samp_collect TEXT, 
	part_plant_animal TEXT, 
	repository_name TEXT, 
	sample_collec_method TEXT, 
	samp_pooling TEXT, 
	samp_rep_biol TEXT, 
	samp_rep_tech TEXT, 
	samp_source_mat_cat TEXT, 
	samp_stor_device TEXT, 
	samp_stor_media TEXT, 
	samp_transport_cont TEXT, 
	samp_transport_dur TEXT, 
	samp_transport_temp TEXT, 
	samp_purpose TEXT, 
	sequencing_kit TEXT, 
	sequencing_location TEXT, 
	serovar_or_serotype TEXT, 
	"spikein_AMR" TEXT, 
	spikein_antibiotic TEXT, 
	spikein_growth_med TEXT, 
	spikein_metal TEXT, 
	spikein_org TEXT, 
	spikein_serovar TEXT, 
	spikein_strain TEXT, 
	study_design TEXT, 
	study_inc_dur TEXT, 
	study_inc_temp TEXT, 
	study_timecourse TEXT, 
	study_tmnt TEXT, 
	timepoint TEXT, 
	misc_param TEXT, 
	PRIMARY KEY (samp_name, project_name, lat_lon, geo_loc_name, collection_date, env_broad_scale, env_local_scale, env_medium, seq_meth, samp_size, samp_collect_device, experimental_factor, nucl_acid_ext, organism_count, spikein_count, samp_stor_temp, samp_stor_dur, samp_vol_we_dna_ext, pool_dna_extracts, "temp", samp_stor_loc, genetic_mod, perturbation, coll_site_geo_feat, food_product_type, "IFSAC_category", ferm_chem_add, ferm_chem_add_perc, ferm_headspace_oxy, ferm_medium, "ferm_pH", ferm_rel_humidity, ferm_temp, ferm_time, ferm_vessel, bacterial_density, cons_food_stor_dur, cons_food_stor_temp, cons_purch_date, cons_qty_purchased, cult_isol_date, cult_result, cult_result_org, cult_target, dietary_claim_use, enrichment_protocol, food_additive, food_allergen_label, food_contact_surf, food_contain_wrap, food_cooking_proc, food_dis_point, food_ingredient, food_name_status, food_origin, food_pack_capacity, food_pack_integrity, food_pack_medium, food_preserv_proc, food_prior_contact, food_prod, food_prod_synonym, food_product_qual, food_quality_date, food_source, food_trace_list, food_trav_mode, food_trav_vehic, food_treat_proc, "HACCP_term", intended_consumer, library_prep_kit, lot_number, microb_cult_med, microb_start, microb_start_count, microb_start_inoc, microb_start_prep, microb_start_source, "microb_start_taxID", nucl_acid_ext_kit, num_samp_collect, part_plant_animal, repository_name, sample_collec_method, samp_pooling, samp_rep_biol, samp_rep_tech, samp_source_mat_cat, samp_stor_device, samp_stor_media, samp_transport_cont, samp_transport_dur, samp_transport_temp, samp_purpose, sequencing_kit, sequencing_location, serovar_or_serotype, "spikein_AMR", spikein_antibiotic, spikein_growth_med, spikein_metal, spikein_org, spikein_serovar, spikein_strain, study_design, study_inc_dur, study_inc_temp, study_timecourse, study_tmnt, timepoint, misc_param)
);

CREATE TABLE "HostAssociated" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	alt TEXT, 
	depth TEXT, 
	elev TEXT, 
	ances_data TEXT, 
	biol_stat TEXT, 
	genetic_mod TEXT, 
	host_common_name TEXT, 
	samp_capt_status TEXT, 
	samp_dis_stage TEXT, 
	host_taxid TEXT, 
	host_subject_id TEXT, 
	host_age TEXT, 
	host_life_stage TEXT, 
	host_sex TEXT, 
	host_disease_stat TEXT, 
	chem_administration TEXT, 
	host_body_habitat TEXT, 
	host_body_site TEXT, 
	host_body_product TEXT, 
	host_tot_mass TEXT, 
	host_height TEXT, 
	host_length TEXT, 
	host_diet TEXT, 
	host_last_meal TEXT, 
	host_growth_cond TEXT, 
	host_substrate TEXT, 
	host_family_relation TEXT, 
	host_subspecf_genlin TEXT, 
	host_genotype TEXT, 
	host_phenotype TEXT, 
	host_body_temp TEXT, 
	host_dry_mass TEXT, 
	blood_press_diast TEXT, 
	blood_press_syst TEXT, 
	host_color TEXT, 
	host_shape TEXT, 
	gravidity TEXT, 
	perturbation TEXT, 
	salinity TEXT, 
	oxy_stat_samp TEXT, 
	"temp" TEXT, 
	organism_count TEXT, 
	samp_vol_we_dna_ext TEXT, 
	samp_store_temp TEXT, 
	samp_store_dur TEXT, 
	samp_store_loc TEXT, 
	host_symbiont TEXT, 
	misc_param TEXT, 
	PRIMARY KEY (samp_name, project_name, alt, depth, elev, ances_data, biol_stat, genetic_mod, host_common_name, samp_capt_status, samp_dis_stage, host_taxid, host_subject_id, host_age, host_life_stage, host_sex, host_disease_stat, chem_administration, host_body_habitat, host_body_site, host_body_product, host_tot_mass, host_height, host_length, host_diet, host_last_meal, host_growth_cond, host_substrate, host_family_relation, host_subspecf_genlin, host_genotype, host_phenotype, host_body_temp, host_dry_mass, blood_press_diast, blood_press_syst, host_color, host_shape, gravidity, perturbation, salinity, oxy_stat_samp, "temp", organism_count, samp_vol_we_dna_ext, samp_store_temp, samp_store_dur, samp_store_loc, host_symbiont, misc_param)
);

CREATE TABLE "HumanAssociated" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	host_subject_id TEXT, 
	host_age TEXT, 
	host_sex TEXT, 
	host_disease_stat TEXT, 
	ihmc_medication_code INTEGER, 
	chem_administration TEXT, 
	host_body_site TEXT, 
	host_body_product TEXT, 
	host_tot_mass TEXT, 
	host_height TEXT, 
	host_diet TEXT, 
	host_last_meal TEXT, 
	host_family_relation TEXT, 
	host_genotype TEXT, 
	host_phenotype TEXT, 
	host_body_temp TEXT, 
	smoker BOOLEAN, 
	host_hiv_stat TEXT, 
	drug_usage TEXT, 
	host_body_mass_index TEXT, 
	diet_last_six_month TEXT, 
	weight_loss_3_month TEXT, 
	ethnicity TEXT, 
	host_occupation TEXT, 
	pet_farm_animal TEXT, 
	travel_out_six_month TEXT, 
	twin_sibling BOOLEAN, 
	medic_hist_perform BOOLEAN, 
	study_complt_stat TEXT, 
	pulmonary_disord TEXT, 
	nose_throat_disord TEXT, 
	blood_blood_disord TEXT, 
	host_pulse TEXT, 
	gestation_state TEXT, 
	maternal_health_stat TEXT, 
	foetal_health_stat TEXT, 
	amniotic_fluid_color TEXT, 
	kidney_disord TEXT, 
	urogenit_tract_disor TEXT, 
	urine_collect_meth TEXT, 
	perturbation TEXT, 
	salinity TEXT, 
	oxy_stat_samp TEXT, 
	"temp" TEXT, 
	organism_count TEXT, 
	samp_vol_we_dna_ext TEXT, 
	samp_store_temp TEXT, 
	samp_store_dur TEXT, 
	host_symbiont TEXT, 
	samp_store_loc TEXT, 
	misc_param TEXT, 
	PRIMARY KEY (samp_name, project_name, host_subject_id, host_age, host_sex, host_disease_stat, ihmc_medication_code, chem_administration, host_body_site, host_body_product, host_tot_mass, host_height, host_diet, host_last_meal, host_family_relation, host_genotype, host_phenotype, host_body_temp, smoker, host_hiv_stat, drug_usage, host_body_mass_index, diet_last_six_month, weight_loss_3_month, ethnicity, host_occupation, pet_farm_animal, travel_out_six_month, twin_sibling, medic_hist_perform, study_complt_stat, pulmonary_disord, nose_throat_disord, blood_blood_disord, host_pulse, gestation_state, maternal_health_stat, foetal_health_stat, amniotic_fluid_color, kidney_disord, urogenit_tract_disor, urine_collect_meth, perturbation, salinity, oxy_stat_samp, "temp", organism_count, samp_vol_we_dna_ext, samp_store_temp, samp_store_dur, host_symbiont, samp_store_loc, misc_param)
);

CREATE TABLE "HumanGut" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	gastrointest_disord TEXT, 
	liver_disord TEXT, 
	special_diet TEXT, 
	host_subject_id TEXT, 
	host_age TEXT, 
	host_sex TEXT, 
	host_disease_stat TEXT, 
	ihmc_medication_code INTEGER, 
	chem_administration TEXT, 
	host_body_site TEXT, 
	host_body_product TEXT, 
	host_tot_mass TEXT, 
	host_height TEXT, 
	host_diet TEXT, 
	host_last_meal TEXT, 
	host_family_relation TEXT, 
	host_genotype TEXT, 
	host_phenotype TEXT, 
	host_body_temp TEXT, 
	host_body_mass_index TEXT, 
	ethnicity TEXT, 
	host_occupation TEXT, 
	medic_hist_perform BOOLEAN, 
	host_pulse TEXT, 
	perturbation TEXT, 
	salinity TEXT, 
	oxy_stat_samp TEXT, 
	"temp" TEXT, 
	organism_count TEXT, 
	samp_store_temp TEXT, 
	samp_vol_we_dna_ext TEXT, 
	samp_store_dur TEXT, 
	host_symbiont TEXT, 
	samp_store_loc TEXT, 
	misc_param TEXT, 
	PRIMARY KEY (samp_name, project_name, gastrointest_disord, liver_disord, special_diet, host_subject_id, host_age, host_sex, host_disease_stat, ihmc_medication_code, chem_administration, host_body_site, host_body_product, host_tot_mass, host_height, host_diet, host_last_meal, host_family_relation, host_genotype, host_phenotype, host_body_temp, host_body_mass_index, ethnicity, host_occupation, medic_hist_perform, host_pulse, perturbation, salinity, oxy_stat_samp, "temp", organism_count, samp_store_temp, samp_vol_we_dna_ext, samp_store_dur, host_symbiont, samp_store_loc, misc_param)
);

CREATE TABLE "HumanOral" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	nose_throat_disord TEXT, 
	time_last_toothbrush TEXT, 
	host_subject_id TEXT, 
	host_age TEXT, 
	host_sex TEXT, 
	host_disease_stat TEXT, 
	ihmc_medication_code INTEGER, 
	chem_administration TEXT, 
	host_body_site TEXT, 
	host_body_product TEXT, 
	host_tot_mass TEXT, 
	host_height TEXT, 
	host_diet TEXT, 
	host_last_meal TEXT, 
	host_family_relation TEXT, 
	host_genotype TEXT, 
	host_phenotype TEXT, 
	host_body_temp TEXT, 
	host_body_mass_index TEXT, 
	ethnicity TEXT, 
	host_occupation TEXT, 
	medic_hist_perform BOOLEAN, 
	host_pulse TEXT, 
	perturbation TEXT, 
	salinity TEXT, 
	oxy_stat_samp TEXT, 
	"temp" TEXT, 
	organism_count TEXT, 
	samp_vol_we_dna_ext TEXT, 
	samp_store_temp TEXT, 
	samp_store_dur TEXT, 
	host_symbiont TEXT, 
	samp_store_loc TEXT, 
	misc_param TEXT, 
	PRIMARY KEY (samp_name, project_name, nose_throat_disord, time_last_toothbrush, host_subject_id, host_age, host_sex, host_disease_stat, ihmc_medication_code, chem_administration, host_body_site, host_body_product, host_tot_mass, host_height, host_diet, host_last_meal, host_family_relation, host_genotype, host_phenotype, host_body_temp, host_body_mass_index, ethnicity, host_occupation, medic_hist_perform, host_pulse, perturbation, salinity, oxy_stat_samp, "temp", organism_count, samp_vol_we_dna_ext, samp_store_temp, samp_store_dur, host_symbiont, samp_store_loc, misc_param)
);

CREATE TABLE "HumanSkin" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	dermatology_disord TEXT, 
	time_since_last_wash TEXT, 
	dominant_hand TEXT, 
	host_subject_id TEXT, 
	host_age TEXT, 
	host_sex TEXT, 
	host_disease_stat TEXT, 
	ihmc_medication_code INTEGER, 
	chem_administration TEXT, 
	host_body_site TEXT, 
	host_body_product TEXT, 
	host_tot_mass TEXT, 
	host_height TEXT, 
	host_diet TEXT, 
	host_last_meal TEXT, 
	host_family_relation TEXT, 
	host_genotype TEXT, 
	host_phenotype TEXT, 
	host_body_temp TEXT, 
	host_body_mass_index TEXT, 
	ethnicity TEXT, 
	host_occupation TEXT, 
	medic_hist_perform BOOLEAN, 
	host_pulse TEXT, 
	perturbation TEXT, 
	salinity TEXT, 
	oxy_stat_samp TEXT, 
	"temp" TEXT, 
	organism_count TEXT, 
	samp_vol_we_dna_ext TEXT, 
	samp_store_temp TEXT, 
	samp_store_dur TEXT, 
	samp_store_loc TEXT, 
	host_symbiont TEXT, 
	misc_param TEXT, 
	PRIMARY KEY (samp_name, project_name, dermatology_disord, time_since_last_wash, dominant_hand, host_subject_id, host_age, host_sex, host_disease_stat, ihmc_medication_code, chem_administration, host_body_site, host_body_product, host_tot_mass, host_height, host_diet, host_last_meal, host_family_relation, host_genotype, host_phenotype, host_body_temp, host_body_mass_index, ethnicity, host_occupation, medic_hist_perform, host_pulse, perturbation, salinity, oxy_stat_samp, "temp", organism_count, samp_vol_we_dna_ext, samp_store_temp, samp_store_dur, samp_store_loc, host_symbiont, misc_param)
);

CREATE TABLE "HumanVaginal" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	menarche TEXT, 
	sexual_act TEXT, 
	pregnancy TEXT, 
	douche TEXT, 
	birth_control TEXT, 
	menopause TEXT, 
	hrt TEXT, 
	hysterectomy BOOLEAN, 
	gynecologic_disord TEXT, 
	urogenit_disord TEXT, 
	host_subject_id TEXT, 
	host_age TEXT, 
	host_sex TEXT, 
	host_disease_stat TEXT, 
	ihmc_medication_code INTEGER, 
	chem_administration TEXT, 
	host_body_site TEXT, 
	host_body_product TEXT, 
	host_tot_mass TEXT, 
	host_height TEXT, 
	host_diet TEXT, 
	host_last_meal TEXT, 
	host_family_relation TEXT, 
	host_genotype TEXT, 
	host_phenotype TEXT, 
	host_body_temp TEXT, 
	host_body_mass_index TEXT, 
	ethnicity TEXT, 
	host_occupation TEXT, 
	medic_hist_perform BOOLEAN, 
	host_pulse TEXT, 
	perturbation TEXT, 
	samp_salinity TEXT, 
	salinity TEXT, 
	oxy_stat_samp TEXT, 
	"temp" TEXT, 
	organism_count TEXT, 
	samp_vol_we_dna_ext TEXT, 
	samp_store_temp TEXT, 
	samp_store_loc TEXT, 
	samp_store_dur TEXT, 
	host_symbiont TEXT, 
	misc_param TEXT, 
	PRIMARY KEY (samp_name, project_name, menarche, sexual_act, pregnancy, douche, birth_control, menopause, hrt, hysterectomy, gynecologic_disord, urogenit_disord, host_subject_id, host_age, host_sex, host_disease_stat, ihmc_medication_code, chem_administration, host_body_site, host_body_product, host_tot_mass, host_height, host_diet, host_last_meal, host_family_relation, host_genotype, host_phenotype, host_body_temp, host_body_mass_index, ethnicity, host_occupation, medic_hist_perform, host_pulse, perturbation, samp_salinity, salinity, oxy_stat_samp, "temp", organism_count, samp_vol_we_dna_ext, samp_store_temp, samp_store_loc, samp_store_dur, host_symbiont, misc_param)
);

CREATE TABLE "HydrocarbonResourcesCores" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	hcr TEXT NOT NULL, 
	hc_produced TEXT NOT NULL, 
	basin TEXT NOT NULL, 
	field TEXT, 
	reservoir TEXT, 
	hcr_temp TEXT NOT NULL, 
	tvdss_of_hcr_temp TEXT, 
	hcr_pressure TEXT, 
	tvdss_of_hcr_press TEXT, 
	permeability TEXT, 
	porosity TEXT, 
	lithology TEXT, 
	depos_env TEXT, 
	hcr_geol_age TEXT, 
	owc_tvdss TEXT, 
	hcr_fw_salinity TEXT, 
	sulfate_fw TEXT NOT NULL, 
	vfa_fw TEXT NOT NULL, 
	sr_kerog_type TEXT, 
	sr_lithology TEXT, 
	sr_dep_env TEXT, 
	sr_geol_age TEXT, 
	samp_well_name TEXT, 
	win TEXT, 
	samp_type TEXT NOT NULL, 
	samp_subtype TEXT, 
	"temp" TEXT NOT NULL, 
	pressure TEXT, 
	samp_tvdss TEXT, 
	samp_md TEXT, 
	elev TEXT, 
	oxy_stat_samp TEXT, 
	samp_transport_cond TEXT, 
	samp_store_temp TEXT, 
	samp_store_dur TEXT, 
	samp_store_loc TEXT, 
	samp_vol_we_dna_ext TEXT, 
	organism_count TEXT, 
	org_count_qpcr_info TEXT, 
	ph FLOAT, 
	salinity TEXT, 
	alkalinity TEXT, 
	alkalinity_method TEXT, 
	sulfate TEXT, 
	sulfide TEXT, 
	tot_sulfur TEXT, 
	nitrate TEXT, 
	nitrite TEXT, 
	ammonium TEXT, 
	tot_nitro TEXT, 
	diss_iron TEXT, 
	sodium TEXT, 
	chloride TEXT, 
	potassium TEXT, 
	magnesium TEXT, 
	calcium TEXT, 
	tot_iron TEXT, 
	diss_org_carb TEXT, 
	diss_inorg_carb TEXT, 
	diss_inorg_phosp TEXT, 
	tot_phosp TEXT, 
	suspend_solids TEXT, 
	density TEXT, 
	diss_carb_dioxide TEXT, 
	diss_oxygen_fluid TEXT, 
	vfa TEXT, 
	benzene TEXT, 
	toluene TEXT, 
	ethylbenzene TEXT, 
	xylene TEXT, 
	api TEXT NOT NULL, 
	tan TEXT, 
	viscosity TEXT, 
	pour_point TEXT, 
	saturates_pc TEXT, 
	aromatics_pc TEXT, 
	resins_pc TEXT, 
	asphaltenes_pc TEXT, 
	misc_param TEXT, 
	additional_info TEXT, 
	PRIMARY KEY (samp_name, project_name, hcr, hc_produced, basin, field, reservoir, hcr_temp, tvdss_of_hcr_temp, hcr_pressure, tvdss_of_hcr_press, permeability, porosity, lithology, depos_env, hcr_geol_age, owc_tvdss, hcr_fw_salinity, sulfate_fw, vfa_fw, sr_kerog_type, sr_lithology, sr_dep_env, sr_geol_age, samp_well_name, win, samp_type, samp_subtype, "temp", pressure, samp_tvdss, samp_md, elev, oxy_stat_samp, samp_transport_cond, samp_store_temp, samp_store_dur, samp_store_loc, samp_vol_we_dna_ext, organism_count, org_count_qpcr_info, ph, salinity, alkalinity, alkalinity_method, sulfate, sulfide, tot_sulfur, nitrate, nitrite, ammonium, tot_nitro, diss_iron, sodium, chloride, potassium, magnesium, calcium, tot_iron, diss_org_carb, diss_inorg_carb, diss_inorg_phosp, tot_phosp, suspend_solids, density, diss_carb_dioxide, diss_oxygen_fluid, vfa, benzene, toluene, ethylbenzene, xylene, api, tan, viscosity, pour_point, saturates_pc, aromatics_pc, resins_pc, asphaltenes_pc, misc_param, additional_info)
);

CREATE TABLE "HydrocarbonResourcesFluidsSwabs" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	hcr TEXT NOT NULL, 
	hc_produced TEXT NOT NULL, 
	basin TEXT NOT NULL, 
	field TEXT, 
	reservoir TEXT, 
	hcr_temp TEXT, 
	tvdss_of_hcr_temp TEXT, 
	hcr_pressure TEXT, 
	tvdss_of_hcr_press TEXT, 
	lithology TEXT, 
	depos_env TEXT, 
	hcr_geol_age TEXT, 
	hcr_fw_salinity TEXT, 
	sulfate_fw TEXT, 
	vfa_fw TEXT, 
	prod_start_date TEXT, 
	prod_rate TEXT, 
	water_prod_rate TEXT, 
	water_cut TEXT NOT NULL, 
	iwf TEXT NOT NULL, 
	add_recov_method TEXT NOT NULL, 
	iw_bt_date_well TEXT, 
	biocide TEXT, 
	biocide_admin_method TEXT, 
	chem_treatment TEXT, 
	chem_treat_method TEXT, 
	samp_loc_corr_rate TEXT, 
	samp_well_name TEXT, 
	win TEXT, 
	samp_type TEXT NOT NULL, 
	samp_subtype TEXT, 
	samp_collect_point TEXT NOT NULL, 
	"temp" TEXT NOT NULL, 
	pressure TEXT, 
	oxy_stat_samp TEXT, 
	samp_preserv TEXT, 
	samp_transport_cond TEXT, 
	samp_store_temp TEXT, 
	samp_store_dur TEXT, 
	samp_store_loc TEXT, 
	samp_vol_we_dna_ext TEXT, 
	organism_count TEXT, 
	org_count_qpcr_info TEXT, 
	ph FLOAT, 
	salinity TEXT, 
	alkalinity TEXT, 
	alkalinity_method TEXT, 
	sulfate TEXT NOT NULL, 
	sulfide TEXT NOT NULL, 
	tot_sulfur TEXT, 
	nitrate TEXT NOT NULL, 
	nitrite TEXT, 
	ammonium TEXT, 
	tot_nitro TEXT, 
	diss_iron TEXT, 
	sodium TEXT, 
	chloride TEXT, 
	potassium TEXT, 
	magnesium TEXT, 
	calcium TEXT, 
	tot_iron TEXT, 
	diss_org_carb TEXT, 
	diss_inorg_carb TEXT, 
	diss_inorg_phosp TEXT, 
	tot_phosp TEXT, 
	suspend_solids TEXT, 
	density TEXT, 
	diss_carb_dioxide TEXT, 
	diss_oxygen_fluid TEXT, 
	vfa TEXT, 
	benzene TEXT, 
	toluene TEXT, 
	ethylbenzene TEXT, 
	xylene TEXT, 
	api TEXT NOT NULL, 
	tan TEXT, 
	viscosity TEXT, 
	pour_point TEXT, 
	saturates_pc TEXT, 
	aromatics_pc TEXT, 
	resins_pc TEXT, 
	asphaltenes_pc TEXT, 
	misc_param TEXT, 
	additional_info TEXT, 
	PRIMARY KEY (samp_name, project_name, hcr, hc_produced, basin, field, reservoir, hcr_temp, tvdss_of_hcr_temp, hcr_pressure, tvdss_of_hcr_press, lithology, depos_env, hcr_geol_age, hcr_fw_salinity, sulfate_fw, vfa_fw, prod_start_date, prod_rate, water_prod_rate, water_cut, iwf, add_recov_method, iw_bt_date_well, biocide, biocide_admin_method, chem_treatment, chem_treat_method, samp_loc_corr_rate, samp_well_name, win, samp_type, samp_subtype, samp_collect_point, "temp", pressure, oxy_stat_samp, samp_preserv, samp_transport_cond, samp_store_temp, samp_store_dur, samp_store_loc, samp_vol_we_dna_ext, organism_count, org_count_qpcr_info, ph, salinity, alkalinity, alkalinity_method, sulfate, sulfide, tot_sulfur, nitrate, nitrite, ammonium, tot_nitro, diss_iron, sodium, chloride, potassium, magnesium, calcium, tot_iron, diss_org_carb, diss_inorg_carb, diss_inorg_phosp, tot_phosp, suspend_solids, density, diss_carb_dioxide, diss_oxygen_fluid, vfa, benzene, toluene, ethylbenzene, xylene, api, tan, viscosity, pour_point, saturates_pc, aromatics_pc, resins_pc, asphaltenes_pc, misc_param, additional_info)
);

CREATE TABLE "MicrobialMatBiofilm" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	depth TEXT, 
	elev TEXT, 
	alkalinity TEXT, 
	alkyl_diethers TEXT, 
	aminopept_act TEXT, 
	ammonium TEXT, 
	bacteria_carb_prod TEXT, 
	biomass TEXT, 
	bishomohopanol TEXT, 
	bromide TEXT, 
	calcium TEXT, 
	carb_nitro_ratio FLOAT, 
	chem_administration TEXT, 
	chloride TEXT, 
	chlorophyll TEXT, 
	diether_lipids TEXT, 
	diss_carb_dioxide TEXT, 
	diss_hydrogen TEXT, 
	diss_inorg_carb TEXT, 
	diss_org_carb TEXT, 
	diss_org_nitro TEXT, 
	diss_oxygen TEXT, 
	glucosidase_act TEXT, 
	magnesium TEXT, 
	mean_frict_vel TEXT, 
	mean_peak_frict_vel TEXT, 
	methane TEXT, 
	misc_param TEXT, 
	n_alkanes TEXT, 
	nitrate TEXT, 
	nitrite TEXT, 
	nitro TEXT, 
	org_carb TEXT, 
	org_matter TEXT, 
	org_nitro TEXT, 
	organism_count TEXT, 
	oxy_stat_samp TEXT, 
	ph FLOAT, 
	part_org_carb TEXT, 
	perturbation TEXT, 
	petroleum_hydrocarb TEXT, 
	phaeopigments TEXT, 
	phosphate TEXT, 
	phosplipid_fatt_acid TEXT, 
	potassium TEXT, 
	pressure TEXT, 
	redox_potential TEXT, 
	salinity TEXT, 
	samp_store_dur TEXT, 
	samp_store_loc TEXT, 
	samp_store_temp TEXT, 
	samp_vol_we_dna_ext TEXT, 
	silicate TEXT, 
	sodium TEXT, 
	sulfate TEXT, 
	sulfide TEXT, 
	"temp" TEXT, 
	tot_carb TEXT, 
	tot_nitro_content TEXT, 
	tot_org_carb TEXT, 
	turbidity TEXT, 
	water_content TEXT, 
	PRIMARY KEY (samp_name, project_name, depth, elev, alkalinity, alkyl_diethers, aminopept_act, ammonium, bacteria_carb_prod, biomass, bishomohopanol, bromide, calcium, carb_nitro_ratio, chem_administration, chloride, chlorophyll, diether_lipids, diss_carb_dioxide, diss_hydrogen, diss_inorg_carb, diss_org_carb, diss_org_nitro, diss_oxygen, glucosidase_act, magnesium, mean_frict_vel, mean_peak_frict_vel, methane, misc_param, n_alkanes, nitrate, nitrite, nitro, org_carb, org_matter, org_nitro, organism_count, oxy_stat_samp, ph, part_org_carb, perturbation, petroleum_hydrocarb, phaeopigments, phosphate, phosplipid_fatt_acid, potassium, pressure, redox_potential, salinity, samp_store_dur, samp_store_loc, samp_store_temp, samp_vol_we_dna_ext, silicate, sodium, sulfate, sulfide, "temp", tot_carb, tot_nitro_content, tot_org_carb, turbidity, water_content)
);

CREATE TABLE "MigsBaPlantAssociated" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	depth TEXT, 
	elev TEXT, 
	air_temp_regm TEXT, 
	ances_data TEXT, 
	antibiotic_regm TEXT, 
	biol_stat TEXT, 
	biotic_regm TEXT, 
	chem_administration TEXT, 
	chem_mutagen TEXT, 
	climate_environment TEXT, 
	cult_root_med TEXT, 
	fertilizer_regm TEXT, 
	fungicide_regm TEXT, 
	gaseous_environment TEXT, 
	genetic_mod TEXT, 
	gravity TEXT, 
	growth_facil TEXT, 
	growth_habit TEXT, 
	growth_hormone_regm TEXT, 
	herbicide_regm TEXT, 
	host_age TEXT, 
	host_common_name TEXT, 
	host_disease_stat TEXT, 
	host_dry_mass TEXT, 
	host_genotype TEXT, 
	host_height TEXT, 
	host_subspecf_genlin TEXT, 
	host_length TEXT, 
	host_life_stage TEXT, 
	host_phenotype TEXT, 
	host_taxid TEXT, 
	host_tot_mass TEXT, 
	host_wet_mass TEXT, 
	humidity_regm TEXT, 
	light_regm TEXT, 
	mechanical_damage TEXT, 
	mineral_nutr_regm TEXT, 
	misc_param TEXT, 
	non_min_nutr_regm TEXT, 
	organism_count TEXT, 
	oxy_stat_samp TEXT, 
	ph_regm TEXT, 
	perturbation TEXT, 
	pesticide_regm TEXT, 
	plant_growth_med TEXT, 
	plant_product TEXT, 
	plant_sex TEXT, 
	plant_struc TEXT, 
	radiation_regm TEXT, 
	rainfall_regm TEXT, 
	root_cond TEXT, 
	root_med_carbon TEXT, 
	root_med_macronutr TEXT, 
	root_med_micronutr TEXT, 
	root_med_suppl TEXT, 
	root_med_ph FLOAT, 
	root_med_regl TEXT, 
	root_med_solid TEXT, 
	salt_regm TEXT, 
	samp_capt_status TEXT, 
	samp_dis_stage TEXT, 
	salinity TEXT, 
	samp_store_dur TEXT, 
	samp_store_loc TEXT, 
	samp_store_temp TEXT, 
	samp_vol_we_dna_ext TEXT, 
	season_environment TEXT, 
	standing_water_regm TEXT, 
	"temp" TEXT, 
	tiss_cult_growth_med TEXT, 
	water_temp_regm TEXT, 
	watering_regm TEXT, 
	host_symbiont TEXT, 
	adapters TEXT, 
	alt TEXT, 
	annot TEXT, 
	assembly_name TEXT, 
	assembly_qual TEXT NOT NULL, 
	assembly_software TEXT NOT NULL, 
	associated_resource TEXT, 
	biotic_relationship TEXT, 
	collection_date TEXT NOT NULL, 
	compl_score TEXT, 
	compl_software TEXT, 
	encoded_traits TEXT, 
	env_broad_scale TEXT NOT NULL, 
	env_local_scale TEXT NOT NULL, 
	env_medium TEXT NOT NULL, 
	estimated_size TEXT, 
	experimental_factor TEXT, 
	extrachrom_elements INTEGER, 
	feat_pred TEXT, 
	geo_loc_name TEXT NOT NULL, 
	host_spec_range INTEGER, 
	isol_growth_condt TEXT NOT NULL, 
	lat_lon TEXT NOT NULL, 
	lib_layout TEXT, 
	lib_reads_seqd INTEGER, 
	lib_screen TEXT, 
	lib_size INTEGER, 
	lib_vector TEXT, 
	neg_cont_type TEXT, 
	nucl_acid_amp TEXT, 
	nucl_acid_ext TEXT, 
	num_replicons INTEGER NOT NULL, 
	number_contig INTEGER NOT NULL, 
	pathogenicity TEXT, 
	pos_cont_type TEXT, 
	ref_biomaterial TEXT NOT NULL, 
	ref_db TEXT, 
	rel_to_oxygen TEXT, 
	samp_collec_device TEXT, 
	samp_collec_method TEXT, 
	samp_mat_process TEXT, 
	samp_size TEXT, 
	samp_taxon_id TEXT NOT NULL, 
	seq_meth TEXT NOT NULL, 
	sim_search_meth TEXT, 
	sop TEXT, 
	source_mat_id TEXT, 
	specific_host TEXT, 
	subspecf_gen_lin TEXT, 
	tax_class TEXT, 
	tax_ident TEXT, 
	trophic_level TEXT, 
	PRIMARY KEY (samp_name, project_name, depth, elev, air_temp_regm, ances_data, antibiotic_regm, biol_stat, biotic_regm, chem_administration, chem_mutagen, climate_environment, cult_root_med, fertilizer_regm, fungicide_regm, gaseous_environment, genetic_mod, gravity, growth_facil, growth_habit, growth_hormone_regm, herbicide_regm, host_age, host_common_name, host_disease_stat, host_dry_mass, host_genotype, host_height, host_subspecf_genlin, host_length, host_life_stage, host_phenotype, host_taxid, host_tot_mass, host_wet_mass, humidity_regm, light_regm, mechanical_damage, mineral_nutr_regm, misc_param, non_min_nutr_regm, organism_count, oxy_stat_samp, ph_regm, perturbation, pesticide_regm, plant_growth_med, plant_product, plant_sex, plant_struc, radiation_regm, rainfall_regm, root_cond, root_med_carbon, root_med_macronutr, root_med_micronutr, root_med_suppl, root_med_ph, root_med_regl, root_med_solid, salt_regm, samp_capt_status, samp_dis_stage, salinity, samp_store_dur, samp_store_loc, samp_store_temp, samp_vol_we_dna_ext, season_environment, standing_water_regm, "temp", tiss_cult_growth_med, water_temp_regm, watering_regm, host_symbiont, adapters, alt, annot, assembly_name, assembly_qual, assembly_software, associated_resource, biotic_relationship, collection_date, compl_score, compl_software, encoded_traits, env_broad_scale, env_local_scale, env_medium, estimated_size, experimental_factor, extrachrom_elements, feat_pred, geo_loc_name, host_spec_range, isol_growth_condt, lat_lon, lib_layout, lib_reads_seqd, lib_screen, lib_size, lib_vector, neg_cont_type, nucl_acid_amp, nucl_acid_ext, num_replicons, number_contig, pathogenicity, pos_cont_type, ref_biomaterial, ref_db, rel_to_oxygen, samp_collec_device, samp_collec_method, samp_mat_process, samp_size, samp_taxon_id, seq_meth, sim_search_meth, sop, source_mat_id, specific_host, subspecf_gen_lin, tax_class, tax_ident, trophic_level)
);

CREATE TABLE "MigsBaSediment" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	depth TEXT NOT NULL, 
	elev TEXT, 
	alkalinity TEXT, 
	alkyl_diethers TEXT, 
	aminopept_act TEXT, 
	ammonium TEXT, 
	bacteria_carb_prod TEXT, 
	biomass TEXT, 
	bishomohopanol TEXT, 
	bromide TEXT, 
	calcium TEXT, 
	carb_nitro_ratio FLOAT, 
	chem_administration TEXT, 
	chloride TEXT, 
	chlorophyll TEXT, 
	density TEXT, 
	diether_lipids TEXT, 
	diss_carb_dioxide TEXT, 
	diss_hydrogen TEXT, 
	diss_inorg_carb TEXT, 
	diss_org_carb TEXT, 
	diss_org_nitro TEXT, 
	diss_oxygen TEXT, 
	glucosidase_act TEXT, 
	magnesium TEXT, 
	mean_frict_vel TEXT, 
	mean_peak_frict_vel TEXT, 
	methane TEXT, 
	misc_param TEXT, 
	n_alkanes TEXT, 
	nitrate TEXT, 
	nitrite TEXT, 
	nitro TEXT, 
	org_carb TEXT, 
	org_matter TEXT, 
	org_nitro TEXT, 
	organism_count TEXT, 
	oxy_stat_samp TEXT, 
	ph FLOAT, 
	particle_class TEXT, 
	part_org_carb TEXT, 
	perturbation TEXT, 
	petroleum_hydrocarb TEXT, 
	phaeopigments TEXT, 
	phosphate TEXT, 
	phosplipid_fatt_acid TEXT, 
	porosity TEXT, 
	potassium TEXT, 
	pressure TEXT, 
	redox_potential TEXT, 
	salinity TEXT, 
	samp_store_dur TEXT, 
	samp_store_loc TEXT, 
	samp_store_temp TEXT, 
	samp_vol_we_dna_ext TEXT, 
	sediment_type TEXT, 
	silicate TEXT, 
	sodium TEXT, 
	sulfate TEXT, 
	sulfide TEXT, 
	"temp" TEXT, 
	tidal_stage TEXT, 
	tot_carb TEXT, 
	tot_depth_water_col TEXT, 
	tot_nitro_content TEXT, 
	tot_org_carb TEXT, 
	turbidity TEXT, 
	water_content TEXT, 
	adapters TEXT, 
	alt TEXT, 
	annot TEXT, 
	assembly_name TEXT, 
	assembly_qual TEXT NOT NULL, 
	assembly_software TEXT NOT NULL, 
	associated_resource TEXT, 
	biotic_relationship TEXT, 
	collection_date TEXT NOT NULL, 
	compl_score TEXT, 
	compl_software TEXT, 
	encoded_traits TEXT, 
	env_broad_scale TEXT NOT NULL, 
	env_local_scale TEXT NOT NULL, 
	env_medium TEXT NOT NULL, 
	estimated_size TEXT, 
	experimental_factor TEXT, 
	extrachrom_elements INTEGER, 
	feat_pred TEXT, 
	geo_loc_name TEXT NOT NULL, 
	host_disease_stat TEXT, 
	host_spec_range INTEGER, 
	isol_growth_condt TEXT NOT NULL, 
	lat_lon TEXT NOT NULL, 
	lib_layout TEXT, 
	lib_reads_seqd INTEGER, 
	lib_screen TEXT, 
	lib_size INTEGER, 
	lib_vector TEXT, 
	neg_cont_type TEXT, 
	nucl_acid_amp TEXT, 
	nucl_acid_ext TEXT, 
	num_replicons INTEGER NOT NULL, 
	number_contig INTEGER NOT NULL, 
	pathogenicity TEXT, 
	pos_cont_type TEXT, 
	ref_biomaterial TEXT NOT NULL, 
	ref_db TEXT, 
	rel_to_oxygen TEXT, 
	samp_collec_device TEXT, 
	samp_collec_method TEXT, 
	samp_mat_process TEXT, 
	samp_size TEXT, 
	samp_taxon_id TEXT NOT NULL, 
	seq_meth TEXT NOT NULL, 
	sim_search_meth TEXT, 
	sop TEXT, 
	source_mat_id TEXT, 
	specific_host TEXT, 
	subspecf_gen_lin TEXT, 
	tax_class TEXT, 
	tax_ident TEXT, 
	trophic_level TEXT, 
	PRIMARY KEY (samp_name, project_name, depth, elev, alkalinity, alkyl_diethers, aminopept_act, ammonium, bacteria_carb_prod, biomass, bishomohopanol, bromide, calcium, carb_nitro_ratio, chem_administration, chloride, chlorophyll, density, diether_lipids, diss_carb_dioxide, diss_hydrogen, diss_inorg_carb, diss_org_carb, diss_org_nitro, diss_oxygen, glucosidase_act, magnesium, mean_frict_vel, mean_peak_frict_vel, methane, misc_param, n_alkanes, nitrate, nitrite, nitro, org_carb, org_matter, org_nitro, organism_count, oxy_stat_samp, ph, particle_class, part_org_carb, perturbation, petroleum_hydrocarb, phaeopigments, phosphate, phosplipid_fatt_acid, porosity, potassium, pressure, redox_potential, salinity, samp_store_dur, samp_store_loc, samp_store_temp, samp_vol_we_dna_ext, sediment_type, silicate, sodium, sulfate, sulfide, "temp", tidal_stage, tot_carb, tot_depth_water_col, tot_nitro_content, tot_org_carb, turbidity, water_content, adapters, alt, annot, assembly_name, assembly_qual, assembly_software, associated_resource, biotic_relationship, collection_date, compl_score, compl_software, encoded_traits, env_broad_scale, env_local_scale, env_medium, estimated_size, experimental_factor, extrachrom_elements, feat_pred, geo_loc_name, host_disease_stat, host_spec_range, isol_growth_condt, lat_lon, lib_layout, lib_reads_seqd, lib_screen, lib_size, lib_vector, neg_cont_type, nucl_acid_amp, nucl_acid_ext, num_replicons, number_contig, pathogenicity, pos_cont_type, ref_biomaterial, ref_db, rel_to_oxygen, samp_collec_device, samp_collec_method, samp_mat_process, samp_size, samp_taxon_id, seq_meth, sim_search_meth, sop, source_mat_id, specific_host, subspecf_gen_lin, tax_class, tax_ident, trophic_level)
);

CREATE TABLE "MigsBaSoil" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	depth TEXT NOT NULL, 
	elev TEXT NOT NULL, 
	cur_land_use TEXT, 
	cur_vegetation TEXT, 
	cur_vegetation_meth TEXT, 
	previous_land_use TEXT, 
	prev_land_use_meth TEXT, 
	crop_rotation TEXT, 
	agrochem_addition TEXT, 
	tillage TEXT, 
	fire TEXT, 
	flooding TEXT, 
	extreme_event TEXT, 
	soil_horizon TEXT, 
	horizon_meth TEXT, 
	sieving TEXT, 
	water_content TEXT, 
	water_cont_soil_meth TEXT, 
	samp_vol_we_dna_ext TEXT, 
	pool_dna_extracts TEXT, 
	store_cond TEXT, 
	link_climate_info TEXT, 
	annual_temp TEXT, 
	season_temp TEXT, 
	annual_precpt TEXT, 
	season_precpt TEXT, 
	link_class_info TEXT, 
	fao_class TEXT, 
	local_class TEXT, 
	local_class_meth TEXT, 
	org_nitro TEXT, 
	"temp" TEXT, 
	soil_type TEXT, 
	soil_type_meth TEXT, 
	slope_gradient TEXT, 
	slope_aspect TEXT, 
	profile_position TEXT, 
	drainage_class TEXT, 
	soil_text_measure TEXT, 
	soil_texture_meth TEXT, 
	ph FLOAT, 
	ph_meth TEXT, 
	org_matter TEXT, 
	tot_org_carb TEXT, 
	tot_org_c_meth TEXT, 
	tot_nitro_content TEXT, 
	tot_nitro_cont_meth TEXT, 
	microbial_biomass TEXT, 
	micro_biomass_meth TEXT, 
	link_addit_analys TEXT, 
	salinity_meth TEXT, 
	heavy_metals TEXT, 
	heavy_metals_meth TEXT, 
	al_sat TEXT, 
	al_sat_meth TEXT, 
	misc_param TEXT, 
	adapters TEXT, 
	alt TEXT, 
	annot TEXT, 
	assembly_name TEXT, 
	assembly_qual TEXT NOT NULL, 
	assembly_software TEXT NOT NULL, 
	associated_resource TEXT, 
	biotic_relationship TEXT, 
	collection_date TEXT NOT NULL, 
	compl_score TEXT, 
	compl_software TEXT, 
	encoded_traits TEXT, 
	env_broad_scale TEXT NOT NULL, 
	env_local_scale TEXT NOT NULL, 
	env_medium TEXT NOT NULL, 
	estimated_size TEXT, 
	experimental_factor TEXT, 
	extrachrom_elements INTEGER, 
	feat_pred TEXT, 
	geo_loc_name TEXT NOT NULL, 
	host_disease_stat TEXT, 
	host_spec_range INTEGER, 
	isol_growth_condt TEXT NOT NULL, 
	lat_lon TEXT NOT NULL, 
	lib_layout TEXT, 
	lib_reads_seqd INTEGER, 
	lib_screen TEXT, 
	lib_size INTEGER, 
	lib_vector TEXT, 
	neg_cont_type TEXT, 
	nucl_acid_amp TEXT, 
	nucl_acid_ext TEXT, 
	num_replicons INTEGER NOT NULL, 
	number_contig INTEGER NOT NULL, 
	pathogenicity TEXT, 
	pos_cont_type TEXT, 
	ref_biomaterial TEXT NOT NULL, 
	ref_db TEXT, 
	rel_to_oxygen TEXT, 
	samp_collec_device TEXT, 
	samp_collec_method TEXT, 
	samp_mat_process TEXT, 
	samp_size TEXT, 
	samp_taxon_id TEXT NOT NULL, 
	seq_meth TEXT NOT NULL, 
	sim_search_meth TEXT, 
	sop TEXT, 
	source_mat_id TEXT, 
	specific_host TEXT, 
	subspecf_gen_lin TEXT, 
	tax_class TEXT, 
	tax_ident TEXT, 
	trophic_level TEXT, 
	PRIMARY KEY (samp_name, project_name, depth, elev, cur_land_use, cur_vegetation, cur_vegetation_meth, previous_land_use, prev_land_use_meth, crop_rotation, agrochem_addition, tillage, fire, flooding, extreme_event, soil_horizon, horizon_meth, sieving, water_content, water_cont_soil_meth, samp_vol_we_dna_ext, pool_dna_extracts, store_cond, link_climate_info, annual_temp, season_temp, annual_precpt, season_precpt, link_class_info, fao_class, local_class, local_class_meth, org_nitro, "temp", soil_type, soil_type_meth, slope_gradient, slope_aspect, profile_position, drainage_class, soil_text_measure, soil_texture_meth, ph, ph_meth, org_matter, tot_org_carb, tot_org_c_meth, tot_nitro_content, tot_nitro_cont_meth, microbial_biomass, micro_biomass_meth, link_addit_analys, salinity_meth, heavy_metals, heavy_metals_meth, al_sat, al_sat_meth, misc_param, adapters, alt, annot, assembly_name, assembly_qual, assembly_software, associated_resource, biotic_relationship, collection_date, compl_score, compl_software, encoded_traits, env_broad_scale, env_local_scale, env_medium, estimated_size, experimental_factor, extrachrom_elements, feat_pred, geo_loc_name, host_disease_stat, host_spec_range, isol_growth_condt, lat_lon, lib_layout, lib_reads_seqd, lib_screen, lib_size, lib_vector, neg_cont_type, nucl_acid_amp, nucl_acid_ext, num_replicons, number_contig, pathogenicity, pos_cont_type, ref_biomaterial, ref_db, rel_to_oxygen, samp_collec_device, samp_collec_method, samp_mat_process, samp_size, samp_taxon_id, seq_meth, sim_search_meth, sop, source_mat_id, specific_host, subspecf_gen_lin, tax_class, tax_ident, trophic_level)
);

CREATE TABLE "MimsPlantAssociated" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	depth TEXT, 
	elev TEXT, 
	air_temp_regm TEXT, 
	ances_data TEXT, 
	antibiotic_regm TEXT, 
	biol_stat TEXT, 
	biotic_regm TEXT, 
	chem_administration TEXT, 
	chem_mutagen TEXT, 
	climate_environment TEXT, 
	cult_root_med TEXT, 
	fertilizer_regm TEXT, 
	fungicide_regm TEXT, 
	gaseous_environment TEXT, 
	genetic_mod TEXT, 
	gravity TEXT, 
	growth_facil TEXT, 
	growth_habit TEXT, 
	growth_hormone_regm TEXT, 
	herbicide_regm TEXT, 
	host_age TEXT, 
	host_common_name TEXT, 
	host_disease_stat TEXT, 
	host_dry_mass TEXT, 
	host_genotype TEXT, 
	host_height TEXT, 
	host_subspecf_genlin TEXT, 
	host_length TEXT, 
	host_life_stage TEXT, 
	host_phenotype TEXT, 
	host_taxid TEXT, 
	host_tot_mass TEXT, 
	host_wet_mass TEXT, 
	humidity_regm TEXT, 
	light_regm TEXT, 
	mechanical_damage TEXT, 
	mineral_nutr_regm TEXT, 
	misc_param TEXT, 
	non_min_nutr_regm TEXT, 
	organism_count TEXT, 
	oxy_stat_samp TEXT, 
	ph_regm TEXT, 
	perturbation TEXT, 
	pesticide_regm TEXT, 
	plant_growth_med TEXT, 
	plant_product TEXT, 
	plant_sex TEXT, 
	plant_struc TEXT, 
	radiation_regm TEXT, 
	rainfall_regm TEXT, 
	root_cond TEXT, 
	root_med_carbon TEXT, 
	root_med_macronutr TEXT, 
	root_med_micronutr TEXT, 
	root_med_suppl TEXT, 
	root_med_ph FLOAT, 
	root_med_regl TEXT, 
	root_med_solid TEXT, 
	salt_regm TEXT, 
	samp_capt_status TEXT, 
	samp_dis_stage TEXT, 
	salinity TEXT, 
	samp_store_dur TEXT, 
	samp_store_loc TEXT, 
	samp_store_temp TEXT, 
	samp_vol_we_dna_ext TEXT, 
	season_environment TEXT, 
	standing_water_regm TEXT, 
	"temp" TEXT, 
	tiss_cult_growth_med TEXT, 
	water_temp_regm TEXT, 
	watering_regm TEXT, 
	host_symbiont TEXT, 
	adapters TEXT, 
	alt TEXT, 
	annot TEXT, 
	assembly_name TEXT, 
	assembly_qual TEXT, 
	assembly_software TEXT, 
	associated_resource TEXT, 
	collection_date TEXT NOT NULL, 
	env_broad_scale TEXT NOT NULL, 
	env_local_scale TEXT NOT NULL, 
	env_medium TEXT NOT NULL, 
	experimental_factor TEXT, 
	feat_pred TEXT, 
	geo_loc_name TEXT NOT NULL, 
	lat_lon TEXT NOT NULL, 
	lib_layout TEXT, 
	lib_reads_seqd INTEGER, 
	lib_screen TEXT, 
	lib_size INTEGER, 
	lib_vector TEXT, 
	mid TEXT, 
	neg_cont_type TEXT, 
	nucl_acid_amp TEXT, 
	nucl_acid_ext TEXT, 
	number_contig INTEGER, 
	pos_cont_type TEXT, 
	ref_biomaterial TEXT, 
	ref_db TEXT, 
	rel_to_oxygen TEXT, 
	samp_collec_device TEXT, 
	samp_collec_method TEXT, 
	samp_mat_process TEXT, 
	samp_size TEXT, 
	samp_taxon_id TEXT NOT NULL, 
	seq_meth TEXT NOT NULL, 
	sim_search_meth TEXT, 
	size_frac TEXT, 
	sop TEXT, 
	source_mat_id TEXT, 
	tax_class TEXT, 
	PRIMARY KEY (samp_name, project_name, depth, elev, air_temp_regm, ances_data, antibiotic_regm, biol_stat, biotic_regm, chem_administration, chem_mutagen, climate_environment, cult_root_med, fertilizer_regm, fungicide_regm, gaseous_environment, genetic_mod, gravity, growth_facil, growth_habit, growth_hormone_regm, herbicide_regm, host_age, host_common_name, host_disease_stat, host_dry_mass, host_genotype, host_height, host_subspecf_genlin, host_length, host_life_stage, host_phenotype, host_taxid, host_tot_mass, host_wet_mass, humidity_regm, light_regm, mechanical_damage, mineral_nutr_regm, misc_param, non_min_nutr_regm, organism_count, oxy_stat_samp, ph_regm, perturbation, pesticide_regm, plant_growth_med, plant_product, plant_sex, plant_struc, radiation_regm, rainfall_regm, root_cond, root_med_carbon, root_med_macronutr, root_med_micronutr, root_med_suppl, root_med_ph, root_med_regl, root_med_solid, salt_regm, samp_capt_status, samp_dis_stage, salinity, samp_store_dur, samp_store_loc, samp_store_temp, samp_vol_we_dna_ext, season_environment, standing_water_regm, "temp", tiss_cult_growth_med, water_temp_regm, watering_regm, host_symbiont, adapters, alt, annot, assembly_name, assembly_qual, assembly_software, associated_resource, collection_date, env_broad_scale, env_local_scale, env_medium, experimental_factor, feat_pred, geo_loc_name, lat_lon, lib_layout, lib_reads_seqd, lib_screen, lib_size, lib_vector, mid, neg_cont_type, nucl_acid_amp, nucl_acid_ext, number_contig, pos_cont_type, ref_biomaterial, ref_db, rel_to_oxygen, samp_collec_device, samp_collec_method, samp_mat_process, samp_size, samp_taxon_id, seq_meth, sim_search_meth, size_frac, sop, source_mat_id, tax_class)
);

CREATE TABLE "MimsSediment" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	depth TEXT NOT NULL, 
	elev TEXT, 
	alkalinity TEXT, 
	alkyl_diethers TEXT, 
	aminopept_act TEXT, 
	ammonium TEXT, 
	bacteria_carb_prod TEXT, 
	biomass TEXT, 
	bishomohopanol TEXT, 
	bromide TEXT, 
	calcium TEXT, 
	carb_nitro_ratio FLOAT, 
	chem_administration TEXT, 
	chloride TEXT, 
	chlorophyll TEXT, 
	density TEXT, 
	diether_lipids TEXT, 
	diss_carb_dioxide TEXT, 
	diss_hydrogen TEXT, 
	diss_inorg_carb TEXT, 
	diss_org_carb TEXT, 
	diss_org_nitro TEXT, 
	diss_oxygen TEXT, 
	glucosidase_act TEXT, 
	magnesium TEXT, 
	mean_frict_vel TEXT, 
	mean_peak_frict_vel TEXT, 
	methane TEXT, 
	misc_param TEXT, 
	n_alkanes TEXT, 
	nitrate TEXT, 
	nitrite TEXT, 
	nitro TEXT, 
	org_carb TEXT, 
	org_matter TEXT, 
	org_nitro TEXT, 
	organism_count TEXT, 
	oxy_stat_samp TEXT, 
	ph FLOAT, 
	particle_class TEXT, 
	part_org_carb TEXT, 
	perturbation TEXT, 
	petroleum_hydrocarb TEXT, 
	phaeopigments TEXT, 
	phosphate TEXT, 
	phosplipid_fatt_acid TEXT, 
	porosity TEXT, 
	potassium TEXT, 
	pressure TEXT, 
	redox_potential TEXT, 
	salinity TEXT, 
	samp_store_dur TEXT, 
	samp_store_loc TEXT, 
	samp_store_temp TEXT, 
	samp_vol_we_dna_ext TEXT, 
	sediment_type TEXT, 
	silicate TEXT, 
	sodium TEXT, 
	sulfate TEXT, 
	sulfide TEXT, 
	"temp" TEXT, 
	tidal_stage TEXT, 
	tot_carb TEXT, 
	tot_depth_water_col TEXT, 
	tot_nitro_content TEXT, 
	tot_org_carb TEXT, 
	turbidity TEXT, 
	water_content TEXT, 
	adapters TEXT, 
	alt TEXT, 
	annot TEXT, 
	assembly_name TEXT, 
	assembly_qual TEXT, 
	assembly_software TEXT, 
	associated_resource TEXT, 
	collection_date TEXT NOT NULL, 
	env_broad_scale TEXT NOT NULL, 
	env_local_scale TEXT NOT NULL, 
	env_medium TEXT NOT NULL, 
	experimental_factor TEXT, 
	feat_pred TEXT, 
	geo_loc_name TEXT NOT NULL, 
	lat_lon TEXT NOT NULL, 
	lib_layout TEXT, 
	lib_reads_seqd INTEGER, 
	lib_screen TEXT, 
	lib_size INTEGER, 
	lib_vector TEXT, 
	mid TEXT, 
	neg_cont_type TEXT, 
	nucl_acid_amp TEXT, 
	nucl_acid_ext TEXT, 
	number_contig INTEGER, 
	pos_cont_type TEXT, 
	ref_biomaterial TEXT, 
	ref_db TEXT, 
	rel_to_oxygen TEXT, 
	samp_collec_device TEXT, 
	samp_collec_method TEXT, 
	samp_mat_process TEXT, 
	samp_size TEXT, 
	samp_taxon_id TEXT NOT NULL, 
	seq_meth TEXT NOT NULL, 
	sim_search_meth TEXT, 
	size_frac TEXT, 
	sop TEXT, 
	source_mat_id TEXT, 
	tax_class TEXT, 
	PRIMARY KEY (samp_name, project_name, depth, elev, alkalinity, alkyl_diethers, aminopept_act, ammonium, bacteria_carb_prod, biomass, bishomohopanol, bromide, calcium, carb_nitro_ratio, chem_administration, chloride, chlorophyll, density, diether_lipids, diss_carb_dioxide, diss_hydrogen, diss_inorg_carb, diss_org_carb, diss_org_nitro, diss_oxygen, glucosidase_act, magnesium, mean_frict_vel, mean_peak_frict_vel, methane, misc_param, n_alkanes, nitrate, nitrite, nitro, org_carb, org_matter, org_nitro, organism_count, oxy_stat_samp, ph, particle_class, part_org_carb, perturbation, petroleum_hydrocarb, phaeopigments, phosphate, phosplipid_fatt_acid, porosity, potassium, pressure, redox_potential, salinity, samp_store_dur, samp_store_loc, samp_store_temp, samp_vol_we_dna_ext, sediment_type, silicate, sodium, sulfate, sulfide, "temp", tidal_stage, tot_carb, tot_depth_water_col, tot_nitro_content, tot_org_carb, turbidity, water_content, adapters, alt, annot, assembly_name, assembly_qual, assembly_software, associated_resource, collection_date, env_broad_scale, env_local_scale, env_medium, experimental_factor, feat_pred, geo_loc_name, lat_lon, lib_layout, lib_reads_seqd, lib_screen, lib_size, lib_vector, mid, neg_cont_type, nucl_acid_amp, nucl_acid_ext, number_contig, pos_cont_type, ref_biomaterial, ref_db, rel_to_oxygen, samp_collec_device, samp_collec_method, samp_mat_process, samp_size, samp_taxon_id, seq_meth, sim_search_meth, size_frac, sop, source_mat_id, tax_class)
);

CREATE TABLE "MimsSoil" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	depth TEXT NOT NULL, 
	elev TEXT NOT NULL, 
	cur_land_use TEXT, 
	cur_vegetation TEXT, 
	cur_vegetation_meth TEXT, 
	previous_land_use TEXT, 
	prev_land_use_meth TEXT, 
	crop_rotation TEXT, 
	agrochem_addition TEXT, 
	tillage TEXT, 
	fire TEXT, 
	flooding TEXT, 
	extreme_event TEXT, 
	soil_horizon TEXT, 
	horizon_meth TEXT, 
	sieving TEXT, 
	water_content TEXT, 
	water_cont_soil_meth TEXT, 
	samp_vol_we_dna_ext TEXT, 
	pool_dna_extracts TEXT, 
	store_cond TEXT, 
	link_climate_info TEXT, 
	annual_temp TEXT, 
	season_temp TEXT, 
	annual_precpt TEXT, 
	season_precpt TEXT, 
	link_class_info TEXT, 
	fao_class TEXT, 
	local_class TEXT, 
	local_class_meth TEXT, 
	org_nitro TEXT, 
	"temp" TEXT, 
	soil_type TEXT, 
	soil_type_meth TEXT, 
	slope_gradient TEXT, 
	slope_aspect TEXT, 
	profile_position TEXT, 
	drainage_class TEXT, 
	soil_text_measure TEXT, 
	soil_texture_meth TEXT, 
	ph FLOAT, 
	ph_meth TEXT, 
	org_matter TEXT, 
	tot_org_carb TEXT, 
	tot_org_c_meth TEXT, 
	tot_nitro_content TEXT, 
	tot_nitro_cont_meth TEXT, 
	microbial_biomass TEXT, 
	micro_biomass_meth TEXT, 
	link_addit_analys TEXT, 
	salinity_meth TEXT, 
	heavy_metals TEXT, 
	heavy_metals_meth TEXT, 
	al_sat TEXT, 
	al_sat_meth TEXT, 
	misc_param TEXT, 
	adapters TEXT, 
	alt TEXT, 
	annot TEXT, 
	assembly_name TEXT, 
	assembly_qual TEXT, 
	assembly_software TEXT, 
	associated_resource TEXT, 
	collection_date TEXT NOT NULL, 
	env_broad_scale TEXT NOT NULL, 
	env_local_scale TEXT NOT NULL, 
	env_medium TEXT NOT NULL, 
	experimental_factor TEXT, 
	feat_pred TEXT, 
	geo_loc_name TEXT NOT NULL, 
	lat_lon TEXT NOT NULL, 
	lib_layout TEXT, 
	lib_reads_seqd INTEGER, 
	lib_screen TEXT, 
	lib_size INTEGER, 
	lib_vector TEXT, 
	mid TEXT, 
	neg_cont_type TEXT, 
	nucl_acid_amp TEXT, 
	nucl_acid_ext TEXT, 
	number_contig INTEGER, 
	pos_cont_type TEXT, 
	ref_biomaterial TEXT, 
	ref_db TEXT, 
	rel_to_oxygen TEXT, 
	samp_collec_device TEXT, 
	samp_collec_method TEXT, 
	samp_mat_process TEXT, 
	samp_size TEXT, 
	samp_taxon_id TEXT NOT NULL, 
	seq_meth TEXT NOT NULL, 
	sim_search_meth TEXT, 
	size_frac TEXT, 
	sop TEXT, 
	source_mat_id TEXT, 
	tax_class TEXT, 
	PRIMARY KEY (samp_name, project_name, depth, elev, cur_land_use, cur_vegetation, cur_vegetation_meth, previous_land_use, prev_land_use_meth, crop_rotation, agrochem_addition, tillage, fire, flooding, extreme_event, soil_horizon, horizon_meth, sieving, water_content, water_cont_soil_meth, samp_vol_we_dna_ext, pool_dna_extracts, store_cond, link_climate_info, annual_temp, season_temp, annual_precpt, season_precpt, link_class_info, fao_class, local_class, local_class_meth, org_nitro, "temp", soil_type, soil_type_meth, slope_gradient, slope_aspect, profile_position, drainage_class, soil_text_measure, soil_texture_meth, ph, ph_meth, org_matter, tot_org_carb, tot_org_c_meth, tot_nitro_content, tot_nitro_cont_meth, microbial_biomass, micro_biomass_meth, link_addit_analys, salinity_meth, heavy_metals, heavy_metals_meth, al_sat, al_sat_meth, misc_param, adapters, alt, annot, assembly_name, assembly_qual, assembly_software, associated_resource, collection_date, env_broad_scale, env_local_scale, env_medium, experimental_factor, feat_pred, geo_loc_name, lat_lon, lib_layout, lib_reads_seqd, lib_screen, lib_size, lib_vector, mid, neg_cont_type, nucl_acid_amp, nucl_acid_ext, number_contig, pos_cont_type, ref_biomaterial, ref_db, rel_to_oxygen, samp_collec_device, samp_collec_method, samp_mat_process, samp_size, samp_taxon_id, seq_meth, sim_search_meth, size_frac, sop, source_mat_id, tax_class)
);

CREATE TABLE "MiscellaneousNaturalOrArtificialEnvironment" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	alt TEXT, 
	depth TEXT, 
	elev TEXT, 
	alkalinity TEXT, 
	ammonium TEXT, 
	biomass TEXT, 
	bromide TEXT, 
	calcium TEXT, 
	chem_administration TEXT, 
	chloride TEXT, 
	chlorophyll TEXT, 
	density TEXT, 
	diether_lipids TEXT, 
	diss_carb_dioxide TEXT, 
	diss_hydrogen TEXT, 
	diss_inorg_carb TEXT, 
	diss_org_nitro TEXT, 
	diss_oxygen TEXT, 
	misc_param TEXT, 
	nitrate TEXT, 
	nitrite TEXT, 
	nitro TEXT, 
	org_carb TEXT, 
	org_matter TEXT, 
	org_nitro TEXT, 
	organism_count TEXT, 
	oxy_stat_samp TEXT, 
	ph FLOAT, 
	perturbation TEXT, 
	phosphate TEXT, 
	phosplipid_fatt_acid TEXT, 
	potassium TEXT, 
	pressure TEXT, 
	salinity TEXT, 
	samp_store_dur TEXT, 
	samp_store_loc TEXT, 
	samp_store_temp TEXT, 
	samp_vol_we_dna_ext TEXT, 
	silicate TEXT, 
	sodium TEXT, 
	sulfate TEXT, 
	sulfide TEXT, 
	"temp" TEXT, 
	water_current TEXT, 
	PRIMARY KEY (samp_name, project_name, alt, depth, elev, alkalinity, ammonium, biomass, bromide, calcium, chem_administration, chloride, chlorophyll, density, diether_lipids, diss_carb_dioxide, diss_hydrogen, diss_inorg_carb, diss_org_nitro, diss_oxygen, misc_param, nitrate, nitrite, nitro, org_carb, org_matter, org_nitro, organism_count, oxy_stat_samp, ph, perturbation, phosphate, phosplipid_fatt_acid, potassium, pressure, salinity, samp_store_dur, samp_store_loc, samp_store_temp, samp_vol_we_dna_ext, silicate, sodium, sulfate, sulfide, "temp", water_current)
);

CREATE TABLE "PlantAssociated" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	depth TEXT, 
	elev TEXT, 
	air_temp_regm TEXT, 
	ances_data TEXT, 
	antibiotic_regm TEXT, 
	biol_stat TEXT, 
	biotic_regm TEXT, 
	chem_administration TEXT, 
	chem_mutagen TEXT, 
	climate_environment TEXT, 
	cult_root_med TEXT, 
	fertilizer_regm TEXT, 
	fungicide_regm TEXT, 
	gaseous_environment TEXT, 
	genetic_mod TEXT, 
	gravity TEXT, 
	growth_facil TEXT, 
	growth_habit TEXT, 
	growth_hormone_regm TEXT, 
	herbicide_regm TEXT, 
	host_age TEXT, 
	host_common_name TEXT, 
	host_disease_stat TEXT, 
	host_dry_mass TEXT, 
	host_genotype TEXT, 
	host_height TEXT, 
	host_subspecf_genlin TEXT, 
	host_length TEXT, 
	host_life_stage TEXT, 
	host_phenotype TEXT, 
	host_taxid TEXT, 
	host_tot_mass TEXT, 
	host_wet_mass TEXT, 
	humidity_regm TEXT, 
	light_regm TEXT, 
	mechanical_damage TEXT, 
	mineral_nutr_regm TEXT, 
	misc_param TEXT, 
	non_min_nutr_regm TEXT, 
	organism_count TEXT, 
	oxy_stat_samp TEXT, 
	ph_regm TEXT, 
	perturbation TEXT, 
	pesticide_regm TEXT, 
	plant_growth_med TEXT, 
	plant_product TEXT, 
	plant_sex TEXT, 
	plant_struc TEXT, 
	radiation_regm TEXT, 
	rainfall_regm TEXT, 
	root_cond TEXT, 
	root_med_carbon TEXT, 
	root_med_macronutr TEXT, 
	root_med_micronutr TEXT, 
	root_med_suppl TEXT, 
	root_med_ph FLOAT, 
	root_med_regl TEXT, 
	root_med_solid TEXT, 
	salt_regm TEXT, 
	samp_capt_status TEXT, 
	samp_dis_stage TEXT, 
	salinity TEXT, 
	samp_store_dur TEXT, 
	samp_store_loc TEXT, 
	samp_store_temp TEXT, 
	samp_vol_we_dna_ext TEXT, 
	season_environment TEXT, 
	standing_water_regm TEXT, 
	"temp" TEXT, 
	tiss_cult_growth_med TEXT, 
	water_temp_regm TEXT, 
	watering_regm TEXT, 
	host_symbiont TEXT, 
	PRIMARY KEY (samp_name, project_name, depth, elev, air_temp_regm, ances_data, antibiotic_regm, biol_stat, biotic_regm, chem_administration, chem_mutagen, climate_environment, cult_root_med, fertilizer_regm, fungicide_regm, gaseous_environment, genetic_mod, gravity, growth_facil, growth_habit, growth_hormone_regm, herbicide_regm, host_age, host_common_name, host_disease_stat, host_dry_mass, host_genotype, host_height, host_subspecf_genlin, host_length, host_life_stage, host_phenotype, host_taxid, host_tot_mass, host_wet_mass, humidity_regm, light_regm, mechanical_damage, mineral_nutr_regm, misc_param, non_min_nutr_regm, organism_count, oxy_stat_samp, ph_regm, perturbation, pesticide_regm, plant_growth_med, plant_product, plant_sex, plant_struc, radiation_regm, rainfall_regm, root_cond, root_med_carbon, root_med_macronutr, root_med_micronutr, root_med_suppl, root_med_ph, root_med_regl, root_med_solid, salt_regm, samp_capt_status, samp_dis_stage, salinity, samp_store_dur, samp_store_loc, samp_store_temp, samp_vol_we_dna_ext, season_environment, standing_water_regm, "temp", tiss_cult_growth_med, water_temp_regm, watering_regm, host_symbiont)
);

CREATE TABLE "Sediment" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	depth TEXT NOT NULL, 
	elev TEXT, 
	alkalinity TEXT, 
	alkyl_diethers TEXT, 
	aminopept_act TEXT, 
	ammonium TEXT, 
	bacteria_carb_prod TEXT, 
	biomass TEXT, 
	bishomohopanol TEXT, 
	bromide TEXT, 
	calcium TEXT, 
	carb_nitro_ratio FLOAT, 
	chem_administration TEXT, 
	chloride TEXT, 
	chlorophyll TEXT, 
	density TEXT, 
	diether_lipids TEXT, 
	diss_carb_dioxide TEXT, 
	diss_hydrogen TEXT, 
	diss_inorg_carb TEXT, 
	diss_org_carb TEXT, 
	diss_org_nitro TEXT, 
	diss_oxygen TEXT, 
	glucosidase_act TEXT, 
	magnesium TEXT, 
	mean_frict_vel TEXT, 
	mean_peak_frict_vel TEXT, 
	methane TEXT, 
	misc_param TEXT, 
	n_alkanes TEXT, 
	nitrate TEXT, 
	nitrite TEXT, 
	nitro TEXT, 
	org_carb TEXT, 
	org_matter TEXT, 
	org_nitro TEXT, 
	organism_count TEXT, 
	oxy_stat_samp TEXT, 
	ph FLOAT, 
	particle_class TEXT, 
	part_org_carb TEXT, 
	perturbation TEXT, 
	petroleum_hydrocarb TEXT, 
	phaeopigments TEXT, 
	phosphate TEXT, 
	phosplipid_fatt_acid TEXT, 
	porosity TEXT, 
	potassium TEXT, 
	pressure TEXT, 
	redox_potential TEXT, 
	salinity TEXT, 
	samp_store_dur TEXT, 
	samp_store_loc TEXT, 
	samp_store_temp TEXT, 
	samp_vol_we_dna_ext TEXT, 
	sediment_type TEXT, 
	silicate TEXT, 
	sodium TEXT, 
	sulfate TEXT, 
	sulfide TEXT, 
	"temp" TEXT, 
	tidal_stage TEXT, 
	tot_carb TEXT, 
	tot_depth_water_col TEXT, 
	tot_nitro_content TEXT, 
	tot_org_carb TEXT, 
	turbidity TEXT, 
	water_content TEXT, 
	PRIMARY KEY (samp_name, project_name, depth, elev, alkalinity, alkyl_diethers, aminopept_act, ammonium, bacteria_carb_prod, biomass, bishomohopanol, bromide, calcium, carb_nitro_ratio, chem_administration, chloride, chlorophyll, density, diether_lipids, diss_carb_dioxide, diss_hydrogen, diss_inorg_carb, diss_org_carb, diss_org_nitro, diss_oxygen, glucosidase_act, magnesium, mean_frict_vel, mean_peak_frict_vel, methane, misc_param, n_alkanes, nitrate, nitrite, nitro, org_carb, org_matter, org_nitro, organism_count, oxy_stat_samp, ph, particle_class, part_org_carb, perturbation, petroleum_hydrocarb, phaeopigments, phosphate, phosplipid_fatt_acid, porosity, potassium, pressure, redox_potential, salinity, samp_store_dur, samp_store_loc, samp_store_temp, samp_vol_we_dna_ext, sediment_type, silicate, sodium, sulfate, sulfide, "temp", tidal_stage, tot_carb, tot_depth_water_col, tot_nitro_content, tot_org_carb, turbidity, water_content)
);

CREATE TABLE "Soil" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	depth TEXT NOT NULL, 
	elev TEXT NOT NULL, 
	cur_land_use TEXT, 
	cur_vegetation TEXT, 
	cur_vegetation_meth TEXT, 
	previous_land_use TEXT, 
	prev_land_use_meth TEXT, 
	crop_rotation TEXT, 
	agrochem_addition TEXT, 
	tillage TEXT, 
	fire TEXT, 
	flooding TEXT, 
	extreme_event TEXT, 
	soil_horizon TEXT, 
	horizon_meth TEXT, 
	sieving TEXT, 
	water_content TEXT, 
	water_cont_soil_meth TEXT, 
	samp_vol_we_dna_ext TEXT, 
	pool_dna_extracts TEXT, 
	store_cond TEXT, 
	link_climate_info TEXT, 
	annual_temp TEXT, 
	season_temp TEXT, 
	annual_precpt TEXT, 
	season_precpt TEXT, 
	link_class_info TEXT, 
	fao_class TEXT, 
	local_class TEXT, 
	local_class_meth TEXT, 
	org_nitro TEXT, 
	"temp" TEXT, 
	soil_type TEXT, 
	soil_type_meth TEXT, 
	slope_gradient TEXT, 
	slope_aspect TEXT, 
	profile_position TEXT, 
	drainage_class TEXT, 
	soil_text_measure TEXT, 
	soil_texture_meth TEXT, 
	ph FLOAT, 
	ph_meth TEXT, 
	org_matter TEXT, 
	tot_org_carb TEXT, 
	tot_org_c_meth TEXT, 
	tot_nitro_content TEXT, 
	tot_nitro_cont_meth TEXT, 
	microbial_biomass TEXT, 
	micro_biomass_meth TEXT, 
	link_addit_analys TEXT, 
	salinity_meth TEXT, 
	heavy_metals TEXT, 
	heavy_metals_meth TEXT, 
	al_sat TEXT, 
	al_sat_meth TEXT, 
	misc_param TEXT, 
	PRIMARY KEY (samp_name, project_name, depth, elev, cur_land_use, cur_vegetation, cur_vegetation_meth, previous_land_use, prev_land_use_meth, crop_rotation, agrochem_addition, tillage, fire, flooding, extreme_event, soil_horizon, horizon_meth, sieving, water_content, water_cont_soil_meth, samp_vol_we_dna_ext, pool_dna_extracts, store_cond, link_climate_info, annual_temp, season_temp, annual_precpt, season_precpt, link_class_info, fao_class, local_class, local_class_meth, org_nitro, "temp", soil_type, soil_type_meth, slope_gradient, slope_aspect, profile_position, drainage_class, soil_text_measure, soil_texture_meth, ph, ph_meth, org_matter, tot_org_carb, tot_org_c_meth, tot_nitro_content, tot_nitro_cont_meth, microbial_biomass, micro_biomass_meth, link_addit_analys, salinity_meth, heavy_metals, heavy_metals_meth, al_sat, al_sat_meth, misc_param)
);

CREATE TABLE "SymbiontAssociated" (
	sample_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	lat_lon TEXT NOT NULL, 
	geo_loc_name TEXT NOT NULL, 
	collection_date TEXT NOT NULL, 
	env_broad_scale TEXT NOT NULL, 
	env_local_scale TEXT NOT NULL, 
	env_medium TEXT NOT NULL, 
	alt TEXT, 
	depth TEXT, 
	elev TEXT, 
	host_subject_id TEXT, 
	host_common_name TEXT, 
	host_taxid TEXT, 
	source_mat_id TEXT, 
	host_dependence TEXT NOT NULL, 
	type_of_symbiosis TEXT, 
	sym_life_cycle_type TEXT NOT NULL, 
	host_life_stage TEXT NOT NULL, 
	host_age TEXT, 
	host_sex TEXT, 
	mode_transmission TEXT, 
	route_transmission TEXT, 
	host_body_habitat TEXT, 
	host_body_site TEXT, 
	host_body_product TEXT, 
	host_tot_mass TEXT, 
	host_height TEXT, 
	host_length TEXT, 
	host_growth_cond TEXT, 
	host_substrate TEXT, 
	host_family_relationship TEXT, 
	host_infra_specific_name TEXT, 
	host_infra_specific_rank TEXT, 
	host_genotype TEXT, 
	host_phenotype TEXT, 
	host_dry_mass TEXT, 
	host_color TEXT, 
	host_shape TEXT, 
	gravidity TEXT, 
	host_number TEXT, 
	host_symbiont TEXT, 
	host_specificity TEXT, 
	symbiont_host_role TEXT, 
	host_cellular_loc TEXT, 
	association_duration TEXT, 
	host_of_host_coinf TEXT, 
	host_of_host_name TEXT, 
	host_of_host_env_loc TEXT, 
	host_of_host_env_med TEXT, 
	host_of_host_taxid INTEGER, 
	host_of_host_sub_id TEXT, 
	host_of_host_disease TEXT, 
	host_of_host_fam_rel TEXT, 
	host_of_host_infname TEXT, 
	host_of_host_infrank TEXT, 
	host_of_host_geno TEXT, 
	host_of_host_pheno TEXT, 
	host_of_host_gravid TEXT, 
	host_of_host_totmass TEXT, 
	chem_administration TEXT, 
	perturbation TEXT, 
	samp_salinity TEXT, 
	oxy_stat_samp TEXT, 
	"temp" TEXT, 
	organism_count TEXT, 
	samp_vol_we_dna_ext TEXT, 
	samp_store_temp TEXT, 
	samp_store_dur TEXT, 
	samp_store_loc TEXT, 
	samp_store_sol TEXT, 
	misc_param TEXT, 
	PRIMARY KEY (sample_name)
);

CREATE TABLE "WastewaterSludge" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	depth TEXT, 
	alkalinity TEXT, 
	biochem_oxygen_dem TEXT, 
	chem_administration TEXT, 
	chem_oxygen_dem TEXT, 
	efficiency_percent TEXT, 
	emulsions TEXT, 
	gaseous_substances TEXT, 
	indust_eff_percent TEXT, 
	inorg_particles TEXT, 
	misc_param TEXT, 
	nitrate TEXT, 
	org_particles TEXT, 
	organism_count TEXT, 
	oxy_stat_samp TEXT, 
	ph FLOAT, 
	perturbation TEXT, 
	phosphate TEXT, 
	pre_treatment TEXT, 
	primary_treatment TEXT, 
	reactor_type TEXT, 
	salinity TEXT, 
	samp_store_dur TEXT, 
	samp_store_loc TEXT, 
	samp_store_temp TEXT, 
	samp_vol_we_dna_ext TEXT, 
	secondary_treatment TEXT, 
	sewage_type TEXT, 
	sludge_retent_time TEXT, 
	sodium TEXT, 
	soluble_inorg_mat TEXT, 
	soluble_org_mat TEXT, 
	suspend_solids TEXT, 
	"temp" TEXT, 
	tertiary_treatment TEXT, 
	tot_nitro TEXT, 
	tot_phosphate TEXT, 
	wastewater_type TEXT, 
	PRIMARY KEY (samp_name, project_name, depth, alkalinity, biochem_oxygen_dem, chem_administration, chem_oxygen_dem, efficiency_percent, emulsions, gaseous_substances, indust_eff_percent, inorg_particles, misc_param, nitrate, org_particles, organism_count, oxy_stat_samp, ph, perturbation, phosphate, pre_treatment, primary_treatment, reactor_type, salinity, samp_store_dur, samp_store_loc, samp_store_temp, samp_vol_we_dna_ext, secondary_treatment, sewage_type, sludge_retent_time, sodium, soluble_inorg_mat, soluble_org_mat, suspend_solids, "temp", tertiary_treatment, tot_nitro, tot_phosphate, wastewater_type)
);

CREATE TABLE "Water" (
	samp_name TEXT NOT NULL, 
	project_name TEXT NOT NULL, 
	depth TEXT NOT NULL, 
	elev TEXT, 
	alkalinity TEXT, 
	alkalinity_method TEXT, 
	alkyl_diethers TEXT, 
	aminopept_act TEXT, 
	ammonium TEXT, 
	atmospheric_data TEXT, 
	bacteria_carb_prod TEXT, 
	bac_prod TEXT, 
	bac_resp TEXT, 
	biomass TEXT, 
	bishomohopanol TEXT, 
	bromide TEXT, 
	calcium TEXT, 
	carb_nitro_ratio FLOAT, 
	chem_administration TEXT, 
	chloride TEXT, 
	chlorophyll TEXT, 
	conduc TEXT, 
	density TEXT, 
	diether_lipids TEXT, 
	diss_carb_dioxide TEXT, 
	diss_hydrogen TEXT, 
	diss_inorg_carb TEXT, 
	diss_inorg_nitro TEXT, 
	diss_inorg_phosp TEXT, 
	diss_org_carb TEXT, 
	diss_org_nitro TEXT, 
	diss_oxygen TEXT, 
	down_par TEXT, 
	fluor TEXT, 
	glucosidase_act TEXT, 
	light_intensity TEXT, 
	magnesium TEXT, 
	mean_frict_vel TEXT, 
	mean_peak_frict_vel TEXT, 
	misc_param TEXT, 
	n_alkanes TEXT, 
	nitrate TEXT, 
	nitrite TEXT, 
	nitro TEXT, 
	org_carb TEXT, 
	org_matter TEXT, 
	org_nitro TEXT, 
	organism_count TEXT, 
	oxy_stat_samp TEXT, 
	ph FLOAT, 
	part_org_carb TEXT, 
	part_org_nitro TEXT, 
	perturbation TEXT, 
	petroleum_hydrocarb TEXT, 
	phaeopigments TEXT, 
	phosphate TEXT, 
	phosplipid_fatt_acid TEXT, 
	photon_flux TEXT, 
	potassium TEXT, 
	pressure TEXT, 
	primary_prod TEXT, 
	redox_potential TEXT, 
	salinity TEXT, 
	samp_store_dur TEXT, 
	samp_store_loc TEXT, 
	samp_store_temp TEXT, 
	samp_vol_we_dna_ext TEXT, 
	silicate TEXT, 
	size_frac_low TEXT, 
	size_frac_up TEXT, 
	sodium TEXT, 
	soluble_react_phosp TEXT, 
	sulfate TEXT, 
	sulfide TEXT, 
	suspend_part_matter TEXT, 
	"temp" TEXT, 
	tidal_stage TEXT, 
	tot_depth_water_col TEXT, 
	tot_diss_nitro TEXT, 
	tot_inorg_nitro TEXT, 
	tot_nitro TEXT, 
	tot_part_carb TEXT, 
	tot_phosp TEXT, 
	turbidity TEXT, 
	water_current TEXT, 
	PRIMARY KEY (samp_name, project_name, depth, elev, alkalinity, alkalinity_method, alkyl_diethers, aminopept_act, ammonium, atmospheric_data, bacteria_carb_prod, bac_prod, bac_resp, biomass, bishomohopanol, bromide, calcium, carb_nitro_ratio, chem_administration, chloride, chlorophyll, conduc, density, diether_lipids, diss_carb_dioxide, diss_hydrogen, diss_inorg_carb, diss_inorg_nitro, diss_inorg_phosp, diss_org_carb, diss_org_nitro, diss_oxygen, down_par, fluor, glucosidase_act, light_intensity, magnesium, mean_frict_vel, mean_peak_frict_vel, misc_param, n_alkanes, nitrate, nitrite, nitro, org_carb, org_matter, org_nitro, organism_count, oxy_stat_samp, ph, part_org_carb, part_org_nitro, perturbation, petroleum_hydrocarb, phaeopigments, phosphate, phosplipid_fatt_acid, photon_flux, potassium, pressure, primary_prod, redox_potential, salinity, samp_store_dur, samp_store_loc, samp_store_temp, samp_vol_we_dna_ext, silicate, size_frac_low, size_frac_up, sodium, soluble_react_phosp, sulfate, sulfide, suspend_part_matter, "temp", tidal_stage, tot_depth_water_col, tot_diss_nitro, tot_inorg_nitro, tot_nitro, tot_part_carb, tot_phosp, turbidity, water_current)
);
